ivis: ivis.main.IvMain Class Reference
ivis.main.IvMain Class Reference
Main (static) class for initialising and shutting down ivis. Should be the first and last ivis command called in your experiment.
Static Public Member Functions
static function checkClassPath ()
Check for bad java class path...
static function assertVersion (vernum)
Validate specified version number against the installed version of ivis.
static function params = validate (paramStructOrXmlFullFileName)
Validate IvConfig parameters.
static function params = initialise (paramStructOrXmlFullFileName)
Load/parse the params (if an xml file file specified), and validate the contents. Must be called prior to launch().
static function [
dataInput , logs ,
InH ,
winhandle , params ] = launch (screennum, InH)
Open connections and ready outputs.
static function pause (InH)
Pause data collection (currently disabled).
static function finishUp (verbosity)
Shut down system and close eye-tracker connection.
static function totalClear ()
Clear mememory.
static function disableScreenChecks ()
Prevent Ivis from checking screen parameters on launch.
Detailed Description
Main (static) class for initialising and shutting down ivis. Should be the first and last ivis command called in your experiment.
IvMain Methods
assertVersion - Validate specified version number against the installed version of ivis.
validate - Validate IvConfig parameters.
initialise - Load/parse the params (if an xml file file specified), and validate the contents. Must be called prior to launch().
launch - Open connections and ready outputs.
pause - Pause data collection (currently disabled).
finishUp - Shut down system and close eye-tracker connection.
totalClear - Clear mememory.
disableScreenChecks - Prevent Ivis from checking screen parameters on launch.
See Also
none
Example
IvMain.initialise(./IvConfig_example.xml); [dataInput, params, winhandle, InH] = IvMain.launch();
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.0 PJ 02/2013 : first_build
Copyright 2014 : P R Jones
Note
This class has the class property Sealed and cannot be derived from.
Definition at line 19 of file IvMain.m.
Member Function Documentation
function ivis.main.IvMain.assertVersion (vernum) static
Validate specified version number against the installed version of ivis.
Parameters
vernum
Date
29/03/13
Author
PRJ
Definition at line 88 of file IvMain.m.
function ivis.main.IvMain.checkClassPath () static
Check for bad java class path...
Date
29/03/13
Author
PRJ
Definition at line 64 of file IvMain.m.
function ivis.main.IvMain.disableScreenChecks () static
Prevent Ivis from checking screen parameters on launch.
Date
29/03/13
Author
PRJ
Definition at line 546 of file IvMain.m.
function ivis.main.IvMain.finishUp (verbosity) static
Shut down system and close eye-tracker connection.
Date
29/03/13
Author
PRJ
Definition at line 431 of file IvMain.m.
References SingletonManager.clearAll(), and ivis.broadcaster.Screen().
Referenced by launch().
function params = ivis.main.IvMain.initialise (paramStructOrXmlFullFileName) static
Load/parse the params (if an xml file file specified), and validate the contents. Must be called prior to launch().
Parameters
paramStructOrXmlFullFileName XML filename (including path) containing parameters, or an equivalent structure
Returns
params IvParams object
Date
29/03/13
Author
PRJ
Definition at line 144 of file IvMain.m.
function [ dataInput , logs , InH , winhandle , params ] = ivis.main.IvMain.launch (screennum, InH) static
Open connections and ready outputs.
Parameters
screennum ######
InH optional existing InputHandler object
Returns
dataInput DataInput object (eyetracker)
logs Raw and Data log objects
InH InputHandler object
winhandle handle to PTB handle
params IvParam object
Date
29/03/13
Author
PRJ
Required fields of InH:
Generated fields of logs:
Definition at line 183 of file IvMain.m.
References finishUp(), ivis.main.IvParams.getInstance(), ivis.main.IvParams.registerScreen(), and ivis.broadcaster.Screen().
function ivis.main.IvMain.pause (InH) static
Pause data collection (currently disabled).
Date
29/03/13
Author
PRJ
Definition at line 417 of file IvMain.m.
function ivis.main.IvMain.totalClear () static
Clear mememory.
Date
29/03/13
Author
PRJ
Definition at line 530 of file IvMain.m.
References clearAbsAll().
function params = ivis.main.IvMain.validate (paramStructOrXmlFullFileName) static
Validate IvConfig parameters.
Parameters
paramStructOrXmlFullFileName XML filename (including path) containing parameters, or an equivalent structure
Returns
params IvParams object
Date
29/03/13
Author
PRJ
Definition at line 113 of file IvMain.m.
The documentation for this class was generated from the following file:
+ivis/+main/IvMain.m