ivis: ivis.gui.IvGUIclassifierGrid Class Reference
ivis.gui.IvGUIclassifierGrid Class Reference
dfadsfdasf.
Public Member Functions
IvGUIclassifierGrid (GUIidx, lMagThresh, poly, categoryObjs)
### blaaaah.
function update (newPlot1Dat, plot2Dat)
### blaaaah.
Public Member Functions inherited from ivis.gui.IvGUIclassifier
function reset ()
### blaaaah.
function printStatus (statusCode, gObjLookingAt)
### blaaaah.
Public Member Functions inherited from ivis.gui.IvGUIelement
function delete ()
### delete.
Static Public Member Functions
static function obj = getInstance ()
static function finishUp ()
Static Public Member Functions inherited from ivis.gui.IvGUIclassifier
static function obj = getInstance ()
static function finishUp ()
Public Attributes
poly
user specified parameters none other internal parameters
nPoly
categoryObjs
nCategoryObjs
Static Public Attributes
static const FIG_NAME = "IvGUIclassifierGrid"
Static Public Attributes inherited from ivis.gui.IvGUIclassifier
static const BUFFER_LENGTH = 100
Static Public Attributes inherited from ivis.gui.IvGUIelement
static const FIG_NAME
Additional Inherited Members
Protected Member Functions inherited from ivis.gui.IvGUIelement
function [
effectiveFDims ,
fDims ,
aDims ] = init (idx, normaliseDims, bgcolor)
Static Protected Member Functions inherited from ivis.gui.IvGUIclassifier
static function obj = getSetSingleton (obj)
Protected Attributes inherited from ivis.gui.IvGUIclassifier
plot1Data
data buffers
plot2Data
nAlternatives
handles
hPlot1Data
hPlot2Data
hPlot2Text
Detailed Description
dfadsfdasf.
dfdfdfdfdfdfdfdfdf
IvGUIclassifierGrid Methods
IvGUIclassifierGrid - Constructor.
update - ffffff.
See Also
none
Example
none
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.1 PJ 02/2013 : converted to Singleton
1.0 PJ 02/2013 : first_build
Todo
rename plots with discriptive names (spatial/temporal rather than plot1 plot2)
Copyright 2014 : P R Jones
Note
This class has the class property Sealed and cannot be derived from.
Definition at line 19 of file IvGUIclassifierGrid.m.
Constructor & Destructor Documentation
ivis.gui.IvGUIclassifierGrid.IvGUIclassifierGrid (GUIidx, lMagThresh, poly, categoryObjs)
### blaaaah.
Parameters
figIndex
lMagThresh
poly
categoryObjs
Returns
IvGUIclassifierGrid
Version
29/03/13 [PJ]
Definition at line 91 of file IvGUIclassifierGrid.m.
References IvHline(), and textLoc().
Member Function Documentation
static function ivis.gui.IvGUIclassifierGrid.finishUp () static
Definition at line 219 of file IvGUIclassifierGrid.m.
References Singleton.finishUpSingleton().
static function obj = ivis.gui.IvGUIclassifierGrid.getInstance () static
Definition at line 215 of file IvGUIclassifierGrid.m.
References Singleton.getInstanceSingleton().
function ivis.gui.IvGUIclassifierGrid.update (newPlot1Dat, plot2Dat) virtual
### blaaaah.
Parameters
newPlot1Dat
plot2Dat
Version
29/03/13 [PJ]
Implements ivis.gui.IvGUIclassifier.
Definition at line 180 of file IvGUIclassifierGrid.m.
Member Data Documentation
ivis.gui.IvGUIclassifierGrid.categoryObjs
Definition at line 79 of file IvGUIclassifierGrid.m.
const ivis.gui.IvGUIclassifierGrid.FIG_NAME = "IvGUIclassifierGrid" static
Definition at line 62 of file IvGUIclassifierGrid.m.
ivis.gui.IvGUIclassifierGrid.nCategoryObjs
Definition at line 80 of file IvGUIclassifierGrid.m.
ivis.gui.IvGUIclassifierGrid.nPoly
Definition at line 78 of file IvGUIclassifierGrid.m.
ivis.gui.IvGUIclassifierGrid.poly
user specified parameters none other internal parameters
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 67 of file IvGUIclassifierGrid.m.
The documentation for this class was generated from the following file:
src/+ivis/+gui/IvGUIclassifierGrid.m