ivis: ivis.eyetracker.IvDataInput Class Reference
ivis.eyetracker.IvDataInput Class Reference abstract
Generic data input class that must be instantiated by a subclass. Handles the crucial data processing task (applying calibration filtering, interpolating, classifying, sending data to logs, etc.).
Public Member Functions
virtual function connect ()
Establish a link to the eyetracking hardware.
virtual function reconnect ()
Disconnect and re-establish link to eyetracker.
virtual function [
n ,
saccadeOnTime ,
blinkTime ] = refresh (logData)
Query the eyetracker for new data; process and store.
virtual function n = flush ()
Query the eyetracker for new data; discard.
function delete ()
IvDataInput Destructor.
function setFixationMarker (fixationMarker)
Establish what, if anything, to use as a gaze-contingent marker. Creates a OpenGL texture if so required (i.e., might alternatively just use the mouse cursor). If none, set obj.showFixations = false, and do nothing.
function updateDriftCorrection (trueXY, estXY, maxCorrection, weight)
Instruct IvCalibration to update the drift correction.
function [
lEyeball_xyzt ,
rEyeball_xyzt ] = getEyeballLocations ()
Get cartesian coordinates for each eyeball, in millimeters.
function [
lastKnownViewingDistance_mm ,
t ] = getLastKnownViewingDistance ()
Compute last known viewing distance (averaging across eyeballs).
function ok = calibrateDistanceToScreen (trueDistance_mm)
Static Public Member Functions
static function
vargout = readRawLog (fullFn)
Parse data stored in a .raw binary file (hardware-brand specific format).
static function validateSubclass (params)
Check that the class name is valid, and that the parameter are congruent for this class.
static function datIn = init (eyetracker, saccade)
Initialise parameters, create GUIS, etc.
static function
dataStruct = readDataLog (fullFn)
Parse data stored in a .csv data file.
static function
lag_msec = estimateLag (params, withTagging, withGUI, Fs)
Estimate expected lag given a specified set of parameters.
static function obj = getInstance ()
static function finishUp ()
Public Attributes
mostRecentSaccadeTime = -inf
mostRecentBlinkTime = -inf
lastXYTV = "[NaN NaN NaN NaN]"
internal parameter for computing speed parameters (shouldn't really be got externally, but is currently used by TrackBox)
lEyeball_xyzt = "[NaN NaN NaN NaN]"
current eyeball location estimates (N.B. distance info is also sotred in the main data buffer, but this record bypasses the buffering process, for added speed). It only records the last known location, however.
rEyeball_xyzt = "[NaN NaN NaN NaN]"
lEyeball_xyzt_raw = "[NaN NaN NaN NaN]"
raw values for trackbox visualisation, where we are happy for values to be blank/invalid (i.e., not interested in last known good value, but want a real time feed)
rEyeball_xyzt_raw = "[NaN NaN NaN NaN]"
trackerInFrontMonitor_mm = 20
z offset (e.g., for TrackBox visualisation)
zCalibrationOffset_mm = 0
trueDistance_mm - currentEstimatedDistance_mm; [NB: should probably not be applied to TrackBox visualisations, in future updates]
Protected Member Functions
IvDataInput ()
IvDataInput Constructor.
function [
saccadeOnTime ,
blinkTime ] = processData (x, y, t, vldty, p, zL_mm, zR_mm, logData)
Interpolate, smooth, log the data, update the GUI and any fixation marker.
function setEyeballLocations (lEye_xyz_mm, rEye_xyz_mm, t)
Set cartesian coordinates for each eyeball, in millimeters.
Protected Member Functions inherited from Singleton
Singleton ()
The internal singleton reference (bit of a hack, thanks to Matlab not having static properties).
Static Protected Member Functions
static function validate ()
Validate initialisation parameters.
static function obj = getSetSingleton (obj)
.
Static Protected Member Functions inherited from Singleton
static function obj = initialise (classname, varargin)
Initialise the Singleton.
static function init = isinit (classname)
Confirm whether the Singleton has been initialised.
static function obj = getInstanceSingleton (classname, varargin)
Get object (only 1 can exist).
static function finishUpSingleton (classname)
Delete object.
Protected Attributes
doBeep
Saccade detection params (move to IvEyeTracker?)
debugMode
saccadeCounter = 0
tmp?
spatialGuiElement
temporalGuiElement
showFixations
useFixationTexture
else use mouse cursor
fixationTexture
fixationTextureRect
xMouseOffset
cf. xOffset in tobiieyex
winhandle
testScreenWidth
testScreenHeight
id
Fs
subclass
eyes
enableTagging
-— TAGGING -—
includeTagsInRawOutput
SACCADE_ON_BITPOS
SACCADE_OFF_BITPOS
BLINK_BITPOS
nDataPoints
nDataPointsPerCycle
nCycles
p1_ww
p1_ww2
p1_iw
p1_Npre
p1_Npost
p2_Npre
p2_Npost
p2_dOffsetPost
p2_dOffsetPrev
distanceCriterion
velocityCriterion
accelCriterion
p3_Npre
p3_Npost
prevSaccadeWindow
prevBlinkWindow
postBlinkWindow
lagPeriod
buffer1
buffer2
buffer3
pixel_per_dg
blinkTemporalMin_secs = 1
0.3;
expectedLatency_sec = 0
-— TIMING -—
LOG_RAW_DATA
-— DATA LOGGING -—
RAWLOG = "[]"
Detailed Description
Generic data input class that must be instantiated by a subclass. Handles the crucial data processing task (applying calibration filtering, interpolating, classifying, sending data to logs, etc.).
n.b. subclasses should NOT repeated the Singleton blurb (if want to be able to access generically, via DataInput.getSingleton()
IvDataInput Abstract Methods
connect - Establish a link to the eyetracking hardware.
reconnect - Disconnect and re-establish link to eyetracker.
refresh - Query the eyetracker for new data; process and store.
flush - Query the eyetracker for new data; discard.
readRawLog- Parse data stored in a .raw binary file (hardware-brand specific format).
validate - Validate initialisation parameters.
IvDataInput Methods
IvDataInput - Constructor.
setFixationMarker - Establish what, if anything, to use as a gaze-contingent marker.
updateDriftCorrection - Instruct IvCalibration to update the drift correction.
getLastKnownXY - Get the last reported xy gaze coordinate (and also the timestamp, if requested).
IvDataInput Static Methods:
validateSubclass - Check that the class name is valid, and that the parameter are congruent for this class.
init - Initialise parameters, create GUIS, etc.
readDataLog - Parse data stored in a .csv data file.
estimateLag - Estimate expected lag given a specified set of parameters.
See Also
none
Example
none
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.0 PJ 02/2013 : first_build
Todo:
discard old points (particularly useful for avoiding slowdowns/dropped-frames?
transfer hardcoded values to IvConfig
discard samples where only 1 eye is available? (re: Sam Wass)
make px2deg mapping dynamic based on subject movement?
in the long run the eyeball z data should be filtered/buffered through this class too. At the moment the logic is internal to each eyetracker, since some trackers don't return this information. But most do now, and it would be good to deal with it properly. This would allow proper retrieval (e.g., get last points since T), and should improve accuracy too (e.g., low pass filtering).
allow setting of trackerInFrontMonitor_mm
Copyright 2014 : P R Jones
Note
This class has the class property Abstract and needs to be inherited in order to be instantiable.
Definition at line 19 of file IvDataInput.m.
Constructor & Destructor Documentation
ivis.eyetracker.IvDataInput.IvDataInput () protected
IvDataInput Constructor.
Returns
obj IvDataInput object
Date
26/06/14
Author
PRJ
Definition at line 571 of file IvDataInput.m.
Member Function Documentation
function ok = ivis.eyetracker.IvDataInput.calibrateDistanceToScreen (trueDistance_mm)
Definition at line 540 of file IvDataInput.m.
function ivis.eyetracker.IvDataInput.connect () pure virtual
Establish a link to the eyetracking hardware.
Date
26/06/14
Author
PRJ
Implemented in ivis.eyetracker.IvSmi, ivis.eyetracker.IvTobii, ivis.eyetracker.IvEyelink, ivis.eyetracker.IvTobiiEyeX, ivis.eyetracker.IvSimulator, ivis.eyetracker.IvMouse, ivis.eyetracker.IvEyeTribe, ivis.eyetracker.IvDummy, and ivis.eyetracker.IvManual.
function ivis.eyetracker.IvDataInput.delete ()
IvDataInput Destructor.
Date
26/06/14
Author
PRJ
Definition at line 361 of file IvDataInput.m.
function lag_msec = ivis.eyetracker.IvDataInput.estimateLag (params, withTagging, withGUI, Fs) static
Estimate expected lag given a specified set of parameters.
e.g., ivis.eyetracker.IvDataInput.computeLag(ivis.main.IvParams.getDefaultConfig(),false,true,500)*1000
Parameters
params
withTagging
withGUI
Fs
Returns
lag_msec
Todo:
compute ivisOverhead empirically
Date
26/06/14
Author
PRJ
Required fields of params:
Definition at line 1324 of file IvDataInput.m.
static function ivis.eyetracker.IvDataInput.finishUp () static
Definition at line 1417 of file IvDataInput.m.
References Singleton.finishUpSingleton().
function n = ivis.eyetracker.IvDataInput.flush () pure virtual
Query the eyetracker for new data; discard.
Date
26/06/14
Author
PRJ
Implemented in ivis.eyetracker.IvSmi, ivis.eyetracker.IvTobii, ivis.eyetracker.IvEyelink, ivis.eyetracker.IvTobiiEyeX, ivis.eyetracker.IvMouse, ivis.eyetracker.IvSimulator, ivis.eyetracker.IvManual, and ivis.eyetracker.IvDummy.
function [ lEyeball_xyzt , rEyeball_xyzt ] = ivis.eyetracker.IvDataInput.getEyeballLocations ()
Get cartesian coordinates for each eyeball, in millimeters.
Returns
lEyeball_xyzt Cartesian coords (mm) + timestamp
rEyeball_xyzt Cartesian coords (mm) + timestamp
Date
21/07/14
Author
PRJ
Definition at line 502 of file IvDataInput.m.
static function obj = ivis.eyetracker.IvDataInput.getInstance () static
Definition at line 1409 of file IvDataInput.m.
References Singleton.getInstanceSingleton().
function [ lastKnownViewingDistance_mm , t ] = ivis.eyetracker.IvDataInput.getLastKnownViewingDistance ()
Compute last known viewing distance (averaging across eyeballs).
Returns
lastKnownViewingDistance_cm distance from eyetracker to eyeball (mm)
Date
21/07/14
Author
PRJ
Definition at line 520 of file IvDataInput.m.
static function obj = ivis.eyetracker.IvDataInput.getSetSingleton (obj) static protected virtual
.
Date
26/06/14
Author
PRJ
Note
This method has non-standard access specifiers: Access = (Singleton)
Implements Singleton.
Definition at line 1401 of file IvDataInput.m.
function datIn = ivis.eyetracker.IvDataInput.init (eyetracker, saccade) static
Initialise parameters, create GUIS, etc.
Parameters
eyetracker
saccade
Returns
datIn
Date
26/06/14
Author
PRJ
Required fields of eyetracker:
Required fields of saccade:
Generated fields of datIn:
Definition at line 1217 of file IvDataInput.m.
References SingletonManager.remove().
function [ saccadeOnTime , blinkTime ] = ivis.eyetracker.IvDataInput.processData (x, y, t, vldty, p, zL_mm, zR_mm, logData) protected
Interpolate, smooth, log the data, update the GUI and any fixation marker.
n.b. Overwrite this file in the subclass instantiation if you want to customise the way data are smoothed/ interpolated/ tagged/ etc.
n.b., input vectors must be columns
Parameters
x : x position (in pixels)
y : y position (in pixels)
t : timestamp (in seconds)
vldty : some kind of validity measure
p : pupil diameter
zL_mm : left eyeball distance
zR_mm : right eyeball distance
logData
Returns
saccadeOnTime
Date
31/07/14
Author
PRJ
Todo:
ought to update pixel_per_dg based on latest position estimate(?)
c : eye-event code (see IvEventCode)
Definition at line 668 of file IvDataInput.m.
function dataStruct = ivis.eyetracker.IvDataInput.readDataLog (fullFn) static
Parse data stored in a .csv data file.
Parameters
fullFn
Returns
dataStruct
Date
26/06/14
Author
PRJ
Definition at line 1301 of file IvDataInput.m.
function vargout = ivis.eyetracker.IvDataInput.readRawLog (fullFn) static pure virtual
Parse data stored in a .raw binary file (hardware-brand specific format).
Parameters
fullFn log (.raw) file, including path
Date
26/06/14
Author
PRJ
Implemented in ivis.eyetracker.IvSmi, ivis.eyetracker.IvTobii, ivis.eyetracker.IvEyelink, ivis.eyetracker.IvTobiiEyeX, ivis.eyetracker.IvMouse, ivis.eyetracker.IvSimulator, ivis.eyetracker.IvEyeTribe, ivis.eyetracker.IvManual, and ivis.eyetracker.IvDummy.
function ivis.eyetracker.IvDataInput.reconnect () pure virtual
Disconnect and re-establish link to eyetracker.
Date
26/06/14
Author
PRJ
Implemented in ivis.eyetracker.IvSmi, ivis.eyetracker.IvTobii, ivis.eyetracker.IvEyelink, ivis.eyetracker.IvTobiiEyeX, ivis.eyetracker.IvEyeTribe, ivis.eyetracker.IvSimulator, ivis.eyetracker.IvMouse, ivis.eyetracker.IvDummy, and ivis.eyetracker.IvManual.
function [ n , saccadeOnTime , blinkTime ] = ivis.eyetracker.IvDataInput.refresh (logData) pure virtual
Query the eyetracker for new data; process and store.
Date
26/06/14
Author
PRJ
Implemented in ivis.eyetracker.IvSmi, ivis.eyetracker.IvEyeTribe, ivis.eyetracker.IvMouse, and ivis.eyetracker.IvDummy.
function ivis.eyetracker.IvDataInput.setEyeballLocations (lEye_xyz_mm, rEye_xyz_mm, t) protected
Set cartesian coordinates for each eyeball, in millimeters.
Parameters
lEye_xyz_mm Cartesian coordinates (mm)
rEye_xyz_mm Cartesian coordinates (mm)
t Timestamp
Date
21/07/14
Author
PRJ
Definition at line 860 of file IvDataInput.m.
function ivis.eyetracker.IvDataInput.setFixationMarker (fixationMarker)
Establish what, if anything, to use as a gaze-contingent marker. Creates a OpenGL texture if so required (i.e., might alternatively just use the mouse cursor). If none, set obj.showFixations = false, and do nothing.
Parameters
fixationMarker none, cursor, or the name of an arbitrary image in ./resources/images/FixationTextures
Date
26/06/14
Author
PRJ
Definition at line 384 of file IvDataInput.m.
References ivis.broadcaster.Screen().
function ivis.eyetracker.IvDataInput.updateDriftCorrection (trueXY, estXY, maxCorrection, weight)
Instruct IvCalibration to update the drift correction.
See Also
ivis.calibration.IvCalibration.updateDriftCorrection()
Parameters
trueXY the "true" xy gaze coordinate
estXY the observed xy gaze coordinate
maxCorrection the maximum acceptable deviation
weight amount of weight to give drift correction (0 to 1)
Todo:
check that this works!
could weight the difference differently depending on the location on the screen?
Date
26/06/14
Author
PRJ
Definition at line 471 of file IvDataInput.m.
function ivis.eyetracker.IvDataInput.validate () static protected pure virtual
Validate initialisation parameters.
Date
26/06/14
Author
PRJ
function ivis.eyetracker.IvDataInput.validateSubclass (params) static
Check that the class name is valid, and that the parameter are congruent for this class.
Parameters
params
Date
26/06/14
Author
PRJ
Required fields of params:
Definition at line 1165 of file IvDataInput.m.
Member Data Documentation
ivis.eyetracker.IvDataInput.accelCriterion protected
Definition at line 313 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.BLINK_BITPOS protected
Definition at line 298 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.blinkTemporalMin_secs = 1 protected
0.3;
Default: 1
Definition at line 324 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.buffer1 protected
Definition at line 320 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.buffer2 protected
Definition at line 321 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.buffer3 protected
Definition at line 322 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.debugMode protected
Definition at line 256 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.distanceCriterion protected
Definition at line 311 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.doBeep protected
Saccade detection params (move to IvEyeTracker?)
Definition at line 250 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.enableTagging protected
-— TAGGING -—
Definition at line 289 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.expectedLatency_sec = 0 protected
-— TIMING -—
Default: 0
Definition at line 332 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.eyes protected
Definition at line 287 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.fixationTexture protected
Definition at line 273 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.fixationTextureRect protected
Definition at line 274 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.Fs protected
Definition at line 285 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.id protected
Definition at line 284 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.includeTagsInRawOutput protected
Definition at line 295 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.lagPeriod protected
Definition at line 319 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.lastXYTV = "[NaN NaN NaN NaN]"
internal parameter for computing speed parameters (shouldn't really be got externally, but is currently used by TrackBox)
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: "[NaN NaN NaN NaN]"
Definition at line 181 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.lEyeball_xyzt = "[NaN NaN NaN NaN]"
current eyeball location estimates (N.B. distance info is also sotred in the main data buffer, but this record bypasses the buffering process, for added speed). It only records the last known location, however.
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: "[NaN NaN NaN NaN]"
Definition at line 194 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.lEyeball_xyzt_raw = "[NaN NaN NaN NaN]"
raw values for trackbox visualisation, where we are happy for values to be blank/invalid (i.e., not interested in last known good value, but want a real time feed)
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: "[NaN NaN NaN NaN]"
Definition at line 210 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.LOG_RAW_DATA protected
-— DATA LOGGING -—
Definition at line 341 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.mostRecentBlinkTime = -inf
Definition at line 178 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.mostRecentSaccadeTime = -inf
Definition at line 176 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.nCycles protected
Definition at line 301 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.nDataPoints protected
Definition at line 299 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.nDataPointsPerCycle protected
Definition at line 300 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.p1_iw protected
Definition at line 304 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.p1_Npost protected
Definition at line 306 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.p1_Npre protected
Definition at line 305 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.p1_ww protected
Definition at line 302 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.p1_ww2 protected
Definition at line 303 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.p2_dOffsetPost protected
Definition at line 309 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.p2_dOffsetPrev protected
Definition at line 310 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.p2_Npost protected
Definition at line 308 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.p2_Npre protected
Definition at line 307 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.p3_Npost protected
Definition at line 315 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.p3_Npre protected
Definition at line 314 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.pixel_per_dg protected
Definition at line 323 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.postBlinkWindow protected
Definition at line 318 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.prevBlinkWindow protected
Definition at line 317 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.prevSaccadeWindow protected
Definition at line 316 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.RAWLOG = "[]" protected
Definition at line 348 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.rEyeball_xyzt = "[NaN NaN NaN NaN]"
Definition at line 208 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.rEyeball_xyzt_raw = "[NaN NaN NaN NaN]"
Definition at line 223 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.SACCADE_OFF_BITPOS protected
Definition at line 297 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.SACCADE_ON_BITPOS protected
Definition at line 296 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.saccadeCounter = 0 protected
tmp?
Default: 0
Definition at line 257 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.showFixations protected
Definition at line 266 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.spatialGuiElement protected
Definition at line 264 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.subclass protected
Definition at line 286 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.temporalGuiElement protected
Definition at line 265 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.testScreenHeight protected
Definition at line 283 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.testScreenWidth protected
Definition at line 282 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.trackerInFrontMonitor_mm = 20
z offset (e.g., for TrackBox visualisation)
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 20
Definition at line 226 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.useFixationTexture protected
else use mouse cursor
Definition at line 267 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.velocityCriterion protected
Definition at line 312 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.winhandle protected
Definition at line 281 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.xMouseOffset protected
cf. xOffset in tobiieyex
Definition at line 275 of file IvDataInput.m.
ivis.eyetracker.IvDataInput.zCalibrationOffset_mm = 0
trueDistance_mm - currentEstimatedDistance_mm; [NB: should probably not be applied to TrackBox visualisations, in future updates]
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 0
Definition at line 237 of file IvDataInput.m.
The documentation for this class was generated from the following file:
+ivis/+eyetracker/IvDataInput.m