ivis: ivis.main.IvParams Class Reference
ivis.main.IvParams Class Reference
Responsible for loading, parsing and validating inputs stored in Config.xml, and storing the system variables so that other aspects of ivis may query them.
Public Member Functions
IvParams (paramStructOrXmlFullFileName, verbosity)
IvParams Constructor.
Static Public Member Functions
static function registerScreen (winhandle)
Update graphic parameters based on the specified PTB screen.
static function params = getDefaultConfig (varargin)
Return the default parameter structure. Individual paramters can be overwritten by specifying pairs of the form: "name",value. E.g., getDefaultConfig(main.verbosity,10).
static function params = getSimpleConfig (varargin)
Return a simple parameter structure, with PTB no screen or GUI. See getDefaultConfig() for details.
static function obj = getInstance ()
static function finishUp ()
static function isIn = isInit ()
Public Attributes
toolboxHomedir
main
graphics
GUI
keyboard
webcam
saccade
classifier
calibration
log
audio
adapt
eyetracker
Static Public Attributes
static const ALLOW_IMPLICIT_CONSTRUCTION = true
whether getInstance() can be called prior to init()
Static Protected Member Functions
static function obj = getSetSingleton (obj)
.
Static Protected Member Functions inherited from Singleton
static function obj = initialise (classname, varargin)
Initialise the Singleton.
static function init = isinit (classname)
Confirm whether the Singleton has been initialised.
static function obj = getInstanceSingleton (classname, varargin)
Get object (only 1 can exist).
static function finishUpSingleton (classname)
Delete object.
Additional Inherited Members
Protected Member Functions inherited from Singleton
Singleton ()
The internal singleton reference (bit of a hack, thanks to Matlab not having static properties).
Detailed Description
Responsible for loading, parsing and validating inputs stored in Config.xml, and storing the system variables so that other aspects of ivis may query them.
IvParams Static Methods
registerScreen - Update graphic parameters based on the specified PTB screen.
getDefaultConfig - Return the default parameter structure.
getSimpleConfig - Return a simple parameter structure.
See Also
none
Example
none
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.0 PJ 02/2013 : first_build
Todo:
: http://www.mathworks.co.uk/help/matlab/matlab_oop/listening-for-changes-to-property-values.html
Copyright 2014 : P R Jones
Note
This class has the class property Sealed and cannot be derived from.
Definition at line 19 of file IvParams.m.
Constructor & Destructor Documentation
ivis.main.IvParams.IvParams (paramStructOrXmlFullFileName, verbosity)
IvParams Constructor.
Parameters
paramStructOrXmlFullFileName
verbosity
Returns
IvParams
Date
26/06/14
Author
PRJ
Definition at line 378 of file IvParams.m.
References ivis.broadcaster.Screen().
Member Function Documentation
static function ivis.main.IvParams.finishUp () static
Definition at line 615 of file IvParams.m.
References Singleton.finishUpSingleton().
function params = ivis.main.IvParams.getDefaultConfig (varargin) static
Return the default parameter structure. Individual paramters can be overwritten by specifying pairs of the form: "name",value. E.g., getDefaultConfig(main.verbosity,10).
Parameters
varargin Any over
Returns
params
Date
26/06/14
Author
PRJ
Generated fields of params:
Definition at line 176 of file IvParams.m.
References ivis.broadcaster.Screen().
static function obj = ivis.main.IvParams.getInstance () static
Definition at line 611 of file IvParams.m.
References Singleton.getInstanceSingleton().
Referenced by ivis.main.IvMain.launch().
static function obj = ivis.main.IvParams.getSetSingleton (obj) static protected virtual
.
Date
26/06/14
Author
PRJ
Note
This method has non-standard access specifiers: Access = (Singleton)
Implements Singleton.
Definition at line 603 of file IvParams.m.
function params = ivis.main.IvParams.getSimpleConfig (varargin) static
Return a simple parameter structure, with PTB no screen or GUI. See getDefaultConfig() for details.
Parameters
varargin Any over
Returns
params
Date
26/06/14
Author
PRJ
Generated fields of params:
Definition at line 321 of file IvParams.m.
static function isIn = ivis.main.IvParams.isInit () static
Definition at line 619 of file IvParams.m.
function ivis.main.IvParams.registerScreen (winhandle) static
Update graphic parameters based on the specified PTB screen.
Parameters
winhandle
Date
26/06/14
Author
PRJ
Definition at line 95 of file IvParams.m.
References ivis.broadcaster.Screen().
Referenced by ivis.main.IvMain.launch().
Member Data Documentation
ivis.main.IvParams.adapt
Definition at line 82 of file IvParams.m.
ivis.main.IvParams.ALLOW_IMPLICIT_CONSTRUCTION = true static
whether getInstance() can be called prior to init()
Default: true
Definition at line 61 of file IvParams.m.
ivis.main.IvParams.audio
Definition at line 81 of file IvParams.m.
ivis.main.IvParams.calibration
Definition at line 79 of file IvParams.m.
ivis.main.IvParams.classifier
Definition at line 78 of file IvParams.m.
ivis.main.IvParams.eyetracker
Definition at line 85 of file IvParams.m.
ivis.main.IvParams.graphics
Definition at line 73 of file IvParams.m.
ivis.main.IvParams.GUI
Definition at line 74 of file IvParams.m.
ivis.main.IvParams.keyboard
Definition at line 75 of file IvParams.m.
ivis.main.IvParams.log
Definition at line 80 of file IvParams.m.
ivis.main.IvParams.main
Definition at line 72 of file IvParams.m.
ivis.main.IvParams.saccade
Definition at line 77 of file IvParams.m.
ivis.main.IvParams.toolboxHomedir
Definition at line 71 of file IvParams.m.
ivis.main.IvParams.webcam
Definition at line 76 of file IvParams.m.
The documentation for this class was generated from the following file:
+ivis/+main/IvParams.m