ivis: ivis.main.IvMain Class Reference
ivis.main.IvMain Class Reference
Main (static) class for initialising and shutting down ivis. Should be the first and last thing called.
Static Public Member Functions
static function assertVersion (vernum)
ASSERTVERSION blaaaah.
static function params = validate (paramStructOrXmlFullFileName)
VALIDATE blaaaah.
static function params = initialise (paramStructOrXmlFullFileName)
INITIALISE Load/parse the params (if an xml file file specified), and validate the contents. Must be called prior to launch().
static function [
dataInput , logs ,
InH ,
winhandle , params ] = launch (winhandle, InH)
LAUNCH dfdfdf.
static function pause (InH)
### blaaaah.
static function finishUp (verbosity)
### blaaaah.
static function totalClear ()
static function disableScreenChecks ()
Detailed Description
Main (static) class for initialising and shutting down ivis. Should be the first and last thing called.
IvMain Methods
finishUp - Shut down system and close eye-tracker connection
initialise - Prepare the system for launch
launch - Open connections and ready outputs
pause - Pause data collection
validate - Validate IvConfig parameters
See Also
none
Example
IvMain.initialise(./IvConfig_example.xml); [dataInput, params, winhandle, InH] = IvMain.launch();
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.0 PJ 02/2013 : first_build
Todo
Lots!
Implement disableScreenChecks
Copyright 2014 : P R Jones
Note
This class has the class property Sealed and cannot be derived from.
Definition at line 19 of file IvMain.m.
Member Function Documentation
function ivis.main.IvMain.assertVersion (vernum) static
ASSERTVERSION blaaaah.
Parameters
vernum
Date
29/03/13
Author
PRJ
Definition at line 99 of file IvMain.m.
static function ivis.main.IvMain.disableScreenChecks () static
Definition at line 573 of file IvMain.m.
function ivis.main.IvMain.finishUp (verbosity) static
### blaaaah.
Date
29/03/13
Author
PRJ
Definition at line 456 of file IvMain.m.
References SingletonManager.clearAll().
Referenced by launch().
function params = ivis.main.IvMain.initialise (paramStructOrXmlFullFileName) static
INITIALISE Load/parse the params (if an xml file file specified), and validate the contents. Must be called prior to launch().
Parameters
paramStructOrXmlFullFileName XML filename (including path) containing parameters, or an equivalent structure
Date
29/03/13
Author
PRJ
Definition at line 155 of file IvMain.m.
References ivisdir().
function [ dataInput , logs , InH , winhandle , params ] = ivis.main.IvMain.launch (winhandle, InH) static
LAUNCH dfdfdf.
Parameters
xmlFullFileName
winhandle
InH
Returns
dataInput
params
Date
29/03/13
Author
PRJ
Required fields of InH:
Generated fields of logs:
Definition at line 189 of file IvMain.m.
References finishUp(), ivis.main.IvParams.getInstance(), and ivis.main.IvParams.updateGraphicParams().
function ivis.main.IvMain.pause (InH) static
### blaaaah.
Date
29/03/13
Author
PRJ
Definition at line 442 of file IvMain.m.
static function ivis.main.IvMain.totalClear () static
Definition at line 565 of file IvMain.m.
References clearAbsAll().
function params = ivis.main.IvMain.validate (paramStructOrXmlFullFileName) static
VALIDATE blaaaah.
Parameters
paramStructOrXmlFullFileName
Returns
params
Date
29/03/13
Author
PRJ
Definition at line 122 of file IvMain.m.
The documentation for this class was generated from the following file:
src/+ivis/+main/IvMain.m