ivis: InputHandler Class Reference
InputHandler Class Reference
DESCRIPTION.
Public Member Functions
InputHandler (isAsynchronous, customQuickKeys, warnUnknownInputsByDefault, winhandle)
CONSTRUCTOR if isAsychronous is true then uses the slow but steady GetChar, otherwise uses the faster KbWait (but at the risk that keystrokes may start & end before the keyboard has been polled. See help KbDemo)
function [
usrInput ,
timeInSecs , x ,
y ] = getInput (newOnly, warnUnknownInputs, suppressQuit)
function
usrInput = mapKeyboardInputToCode (keyboardInput, mouseInput, warnUnknownInputs, suppressQuit)
would be nice to also return the input objects, not just a vector of codes
function
inputObjs = mapCodeToInputObj (codes)
validate that potential inputs are all recognised
function [
usrInputCode ,
timeInSecs , x ,
y ] = waitForInput (specificInputCodes, promptText, warnUnknownInputs)
parse inputs and substitute default values where required
function [
keyCode ,
timeInSecs ] = waitForKeystroke (specificKey)
function removeFocus ()
function updateFocus ()
function delete ()
restore input
Static Public Member Functions
static function test ()
static function obj = getInstance ()
static function finishUp ()
Public Attributes
winhandle = "[]"
user defined
isAsynchronous = true
warnUnknownInputsByDefault = true
isPaused = 0
other
Static Public Attributes
static const INPT_NULL = struct("'key',[], 'code',-1")
static const INPT_MISC = struct("'key',[], 'code',-2")
static const INPT_CLICK = struct("'key','leftclick', 'code',-3")
static const INPT_RIGHTCLICK = struct("'key','rightclick', 'code',-4")
static const INPT_PAUSE = struct("'key','p', 'code',-5")
static const INPT_QUIT = struct("'key','escape', 'code',-99")
static const INPT_SPACE = struct("'key','space', 'code',-6")
useful to have 1 key
static const INPT_RETURN = struct("'key','Return', 'code',-7")
useful to have a 2nd key
static const INPT_RECONNECT = struct("'key','o', 'code',-8")
Static Protected Member Functions
static function obj = getSetSingleton (obj)
Static Protected Member Functions inherited from Singleton
static function obj = initialise (classname, varargin)
static function init = isinit (classname)
static function obj = getInstanceSingleton (classname, varargin)
static function finishUpSingleton (classname)
Additional Inherited Members
Protected Member Functions inherited from Singleton
Singleton ()
Detailed Description
DESCRIPTION.
Definition at line 17 of file InputHandler.m.
Constructor & Destructor Documentation
InputHandler.InputHandler (isAsynchronous, customQuickKeys, warnUnknownInputsByDefault, winhandle)
CONSTRUCTOR if isAsychronous is true then uses the slow but steady GetChar, otherwise uses the faster KbWait (but at the risk that keystrokes may start & end before the keyboard has been polled. See help KbDemo)
Definition at line 96 of file InputHandler.m.
References isAsynchronous, warnUnknownInputsByDefault, and winhandle.
Referenced by MyInputHandler.MyInputHandler(), and test().
Member Function Documentation
function InputHandler.delete ()
restore input
Definition at line 453 of file InputHandler.m.
static function InputHandler.finishUp () static
Definition at line 538 of file InputHandler.m.
References Singleton.finishUpSingleton().
function [usrInput , timeInSecs , x , y ] = InputHandler.getInput (newOnly, warnUnknownInputs, suppressQuit)
Definition at line 167 of file InputHandler.m.
static function obj = InputHandler.getInstance () static
Definition at line 534 of file InputHandler.m.
References Singleton.getInstanceSingleton().
static function obj = InputHandler.getSetSingleton (obj) static protected virtual
Implements Singleton.
Definition at line 526 of file InputHandler.m.
function inputObjs = InputHandler.mapCodeToInputObj (codes)
validate that potential inputs are all recognised
Definition at line 358 of file InputHandler.m.
function usrInput = InputHandler.mapKeyboardInputToCode (keyboardInput, mouseInput, warnUnknownInputs, suppressQuit)
would be nice to also return the input objects, not just a vector of codes
Definition at line 272 of file InputHandler.m.
References INPT_NULL.
function InputHandler.removeFocus ()
Definition at line 443 of file InputHandler.m.
static function InputHandler.test () static
Definition at line 504 of file InputHandler.m.
References InputHandler().
function InputHandler.updateFocus ()
Definition at line 448 of file InputHandler.m.
function [ usrInputCode , timeInSecs , x , y ] = InputHandler.waitForInput (specificInputCodes, promptText, warnUnknownInputs)
parse inputs and substitute default values where required
Required fields of specificInputCodes:
Definition at line 376 of file InputHandler.m.
function [keyCode , timeInSecs ] = InputHandler.waitForKeystroke (specificKey)
Definition at line 429 of file InputHandler.m.
Member Data Documentation
const InputHandler.INPT_CLICK = struct("'key','leftclick', 'code',-3") static
Definition at line 30 of file InputHandler.m.
const InputHandler.INPT_MISC = struct("'key',[], 'code',-2") static
Definition at line 29 of file InputHandler.m.
const InputHandler.INPT_NULL = struct("'key',[], 'code',-1") static
Definition at line 28 of file InputHandler.m.
Referenced by mapKeyboardInputToCode().
const InputHandler.INPT_PAUSE = struct("'key','p', 'code',-5") static
Definition at line 32 of file InputHandler.m.
const InputHandler.INPT_QUIT = struct("'key','escape', 'code',-99") static
Definition at line 33 of file InputHandler.m.
const InputHandler.INPT_RECONNECT = struct("'key','o', 'code',-8") static
Definition at line 48 of file InputHandler.m.
InputHandler.INPT_RETURN = struct("'key','Return', 'code',-7") static
useful to have a 2nd key
Default: struct("'key','Return', 'code',-7")
Definition at line 41 of file InputHandler.m.
const InputHandler.INPT_RIGHTCLICK = struct("'key','rightclick', 'code',-4") static
Definition at line 31 of file InputHandler.m.
InputHandler.INPT_SPACE = struct("'key','space', 'code',-6") static
useful to have 1 key
Default: struct("'key','space', 'code',-6")
Definition at line 34 of file InputHandler.m.
InputHandler.isAsynchronous = true
Definition at line 62 of file InputHandler.m.
Referenced by InputHandler().
InputHandler.isPaused = 0
other
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 0
Definition at line 66 of file InputHandler.m.
InputHandler.warnUnknownInputsByDefault = true
Definition at line 64 of file InputHandler.m.
Referenced by InputHandler().
InputHandler.winhandle = "[]"
user defined
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: "[]"
Definition at line 51 of file InputHandler.m.
Referenced by InputHandler(), ivisDemo005_usingaPTBScreen(), ivisDemo006_trackboxVisualisation(), ivisDemo007_classifyingFixations(), ivisDemo008_playingVideos(), ivisDemo009_streamingWebcams(), ivisDemo011_advancedClassifiers(), and ivisDemo012_externalConfigFiles().
The documentation for this class was generated from the following file:
src/ivis_util/InputHandler.m