ivis: ivis.calibration.TrackBox Class Reference
ivis.calibration.TrackBox Class Reference
Display Tobii eyetracker box schema and current eyeball info.
Public Member Functions
TrackBox ()
TrackBox Constructor.
function delete ()
IvWebcam Desctructor.
function draw (unused1, unused2)
.
function start ()
.
function stop ()
.
function toggle ()
Re-added PJ: 01/05/15.
Public Member Functions inherited from ivis.broadcaster.IvListener
function delete ()
Object destructor.
function startListening (eventName, functionHandle)
Inform broadcaster to execute the specified functionHandle whenever a given event with name eventName occurs.
function stopListening (eventName)
Stop listening to broadcast event.
function toggleListening (eventName, functionHandle)
Toggle whether or not subscribed to event (if not already subscribed a valid function handle must be supplied).
function startListeningTo (hostObj, hostProperty, eventName, functionHandle)
Add a listener for a property change in a given object.
Static Public Member Functions
static function obj = getInstance ()
static function finishUp ()
Public Attributes
winhandle
eyeTracker
monitorwidth_mm = 600
monitorheight_mm = 330
monitorwidth_px
monitorheight_px
trackerInFrontMonitor_mm
boxdist_mm
boxsize_mm
amax
Public Attributes inherited from ivis.broadcaster.IvListener
listenerHandles = {""}
listener handles
eventNames = {""}
event names
Static Public Attributes
static const ALLOW_IMPLICIT_CONSTRUCTION = true
Static Protected Member Functions
static function obj = getSetSingleton (obj)
.
Static Protected Member Functions inherited from Singleton
static function obj = initialise (classname, varargin)
Initialise the Singleton.
static function init = isinit (classname)
Confirm whether the Singleton has been initialised.
static function obj = getInstanceSingleton (classname, varargin)
Get object (only 1 can exist).
static function finishUpSingleton (classname)
Delete object.
Additional Inherited Members
Protected Member Functions inherited from Singleton
Singleton ()
The internal singleton reference (bit of a hack, thanks to Matlab not having static properties).
Detailed Description
Display Tobii eyetracker box schema and current eyeball info.
Utility function that displays a scale wireframe model of the display screen and Tobii x120 trackbox. Estimated eyeball and fixation positions are displayed, or the wireframe is turned red if no input is detected. The screen parameters are taken from IvParams. However, the track box dimensions are guestimated and hardcoded, since they cannot be extracted from the Tobii given the current matlab SDK bindings.
TrackBox Methods
draw - Draw trackbox, and keep updating until stopped
stop - Stop drawing trackbox and release memory
toggle - Alternate between start/stop states
See Also
none
Example
none
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.0 PJ 03/2013 : first_build
@ todo: many values are currently hard coded ? (e.g., screen dimensions)
Copyright 2014 : P R Jones
Note
This class has the class property Sealed and cannot be derived from.
Definition at line 19 of file TrackBox.m.
Constructor & Destructor Documentation
ivis.calibration.TrackBox.TrackBox ()
TrackBox Constructor.
Returns
obj TrackBox object
Date
26/06/14
Author
PRJ
Definition at line 176 of file TrackBox.m.
References ivis.broadcaster.Screen().
Member Function Documentation
function ivis.calibration.TrackBox.delete ()
IvWebcam Desctructor.
Date
26/06/14
Author
PRJ
Definition at line 281 of file TrackBox.m.
function ivis.calibration.TrackBox.draw (unused1, unused2)
.
Date
26/06/14
Author
PRJ
Parameters
unused1 Marked as "~" in original m-file.
unused2 Marked as "~" in original m-file.
Definition at line 296 of file TrackBox.m.
References ivis.broadcaster.Screen().
static function ivis.calibration.TrackBox.finishUp () static
Definition at line 624 of file TrackBox.m.
References Singleton.finishUpSingleton().
static function obj = ivis.calibration.TrackBox.getInstance () static
Definition at line 620 of file TrackBox.m.
References Singleton.getInstanceSingleton().
static function obj = ivis.calibration.TrackBox.getSetSingleton (obj) static protected virtual
.
Date
26/06/14
Author
PRJ
Note
This method has non-standard access specifiers: Access = (Singleton)
Implements Singleton.
Definition at line 612 of file TrackBox.m.
function ivis.calibration.TrackBox.start ()
.
Date
26/06/14
Author
PRJ
Definition at line 400 of file TrackBox.m.
function ivis.calibration.TrackBox.stop ()
.
Date
26/06/14
Author
PRJ
Definition at line 414 of file TrackBox.m.
function ivis.calibration.TrackBox.toggle ()
Re-added PJ: 01/05/15.
Definition at line 428 of file TrackBox.m.
Member Data Documentation
const ivis.calibration.TrackBox.ALLOW_IMPLICIT_CONSTRUCTION = true static
Definition at line 69 of file TrackBox.m.
ivis.calibration.TrackBox.amax
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 157 of file TrackBox.m.
ivis.calibration.TrackBox.boxdist_mm
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 139 of file TrackBox.m.
ivis.calibration.TrackBox.boxsize_mm
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 148 of file TrackBox.m.
ivis.calibration.TrackBox.eyeTracker
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 83 of file TrackBox.m.
ivis.calibration.TrackBox.monitorheight_mm = 330
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 330
Definition at line 102 of file TrackBox.m.
ivis.calibration.TrackBox.monitorheight_px
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 121 of file TrackBox.m.
ivis.calibration.TrackBox.monitorwidth_mm = 600
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 600
Definition at line 92 of file TrackBox.m.
ivis.calibration.TrackBox.monitorwidth_px
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 112 of file TrackBox.m.
ivis.calibration.TrackBox.trackerInFrontMonitor_mm
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 130 of file TrackBox.m.
ivis.calibration.TrackBox.winhandle
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 74 of file TrackBox.m.
The documentation for this class was generated from the following file:
+ivis/+calibration/TrackBox.m