ivis: ivis.gui.IvGUIclassifierVector Class Reference
ivis.gui.IvGUIclassifierVector Class Reference
Singleton for displaying vector classifier parameters and status.
Public Member Functions
IvGUIclassifierVector (GUIidx, rqdMagnitude, direction)
IvGUIclassifierVector Constructor.
function update (newPlot1Dat, plot2Dat, theta, rho)
Update figure window.
Public Member Functions inherited from ivis.gui.IvGUIclassifier
virtual function update (newPlot1Dat, plot2Dat, varargin)
Update figure window.
function reset ()
Reset the classifier panel; clear any accumulated data.
function printStatus (statusCode, gObjLookingAt)
Write the classification estimate to the panel.
Public Member Functions inherited from ivis.gui.IvGUIelement
function delete ()
IvGUIelement Destructor.
Static Public Member Functions
static function obj = getInstance ()
static function finishUp ()
Static Public Member Functions inherited from ivis.gui.IvGUIclassifier
static function obj = getInstance ()
static function finishUp ()
Public Attributes
arrow
Static Public Attributes
static const FIG_NAME = "IvGUIclassifierVector"
Static Public Attributes inherited from ivis.gui.IvGUIclassifier
static const BUFFER_LENGTH_PLOT1 = 3
upper plot
static const BUFFER_LENGTH_PLOT2 = 100
lower plot
Static Public Attributes inherited from ivis.gui.IvGUIelement
static const FIG_NAME
Static Protected Member Functions
static function obj = getSetSingleton (obj)
.
Additional Inherited Members
Protected Member Functions inherited from ivis.gui.IvGUIelement
function [
effectiveFDims ,
fDims ,
aDims ] = init (GUIidx, normaliseDims, bgcolor)
Initialise the GUI element; set the renderer and compute the plot area dimensions.
Protected Attributes inherited from ivis.gui.IvGUIclassifier
plot1Data
data buffers top panel data (location)
plot2Data
bottom panel data (evidence)
nAlternatives
integer num hypotheses handles
hPlot1Data
top panel data handle
hPlot2Data
bottom panel data handle
hPlot2Text
bottom panel text handle
Detailed Description
Singleton for displaying vector classifier parameters and status.
IvGUIclassifierVector Methods
IvGUIclassifierVector - Constructor.
update - Update figure window.
See Also
ivis.classifier.IvClassifierVector
Example
none
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.1 PJ 02/2013 : converted to Singleton
1.0 PJ 02/2013 : first_build
Todo:
rename plots with discriptive names (spatial/temporal rather than plot1 plot2)
Wind_rose.m for a fancier/forced-alternative version?
Copyright 2014 : P R Jones
Note
This class has the class property Sealed and cannot be derived from.
Definition at line 19 of file IvGUIclassifierVector.m.
Constructor & Destructor Documentation
ivis.gui.IvGUIclassifierVector.IvGUIclassifierVector (GUIidx, rqdMagnitude, direction)
IvGUIclassifierVector Constructor.
Parameters
GUIidx GUI frame index
rqdMagnitude evidence threshold required for decision
direction target direction to check against
Returns
obj IvGUIclassifierVector object
Date
26/06/14
Author
PRJ
Definition at line 76 of file IvGUIclassifierVector.m.
References cmp2pol().
Member Function Documentation
static function ivis.gui.IvGUIclassifierVector.finishUp () static
Definition at line 192 of file IvGUIclassifierVector.m.
References Singleton.finishUpSingleton().
static function obj = ivis.gui.IvGUIclassifierVector.getInstance () static
Definition at line 188 of file IvGUIclassifierVector.m.
References Singleton.getInstanceSingleton().
static function obj = ivis.gui.IvGUIclassifierVector.getSetSingleton (obj) static protected virtual
.
Date
26/06/14
Author
PRJ
Note
This method has non-standard access specifiers: Access = (Singleton)
Reimplemented from ivis.gui.IvGUIclassifier.
Definition at line 180 of file IvGUIclassifierVector.m.
function ivis.gui.IvGUIclassifierVector.update (newPlot1Dat, plot2Dat, theta, rho)
Update figure window.
Parameters
newPlot1Dat graphic & gaze locations
plot2Dat evidence
theta current vector-direction estimate
rho current vector-magnitude estimate
Date
26/06/14
Author
PRJ
Definition at line 145 of file IvGUIclassifierVector.m.
Member Data Documentation
ivis.gui.IvGUIclassifierVector.arrow
Definition at line 65 of file IvGUIclassifierVector.m.
const ivis.gui.IvGUIclassifierVector.FIG_NAME = "IvGUIclassifierVector" static
Definition at line 60 of file IvGUIclassifierVector.m.
The documentation for this class was generated from the following file:
+ivis/+gui/IvGUIclassifierVector.m