ivis: ivisdir.m File Reference
ivisdir.m File Reference
Functions
function dir = ivisdir ()
Function Documentation
function dir = ivisdir ()
Definition at line 17 of file ivisdir.m.
Referenced by ivis.main.IvMain.initialise(), ivisDemo008_playingVideos(), ivisDemo010_readingRawGazeData(), ivisDemo012_externalConfigFiles(), ivisDemo_audio(), ivisDemos_runall(), and ivis.log.IvLog.validateFn().