ivis: admin/RUN_ME.m File Reference
RUN_ME.m File Reference
% Convert src code into (encrypted) p-code, save outputs in bin/
Functions
function RUN_ME ()
% Convert src code into (encrypted) p-code, save outputs in bin/
Detailed Description
% Convert src code into (encrypted) p-code, save outputs in bin/
Definition in file RUN_ME.m.
Function Documentation
function RUN_ME ()
% Convert src code into (encrypted) p-code, save outputs in bin/
Definition at line 17 of file RUN_ME.m.
References MatlabDocMaker.create(), deploypcode(), and ivisdir().