ivis: ivis.graphic.IvGraphic Class Reference
ivis.graphic.IvGraphic Class Reference
Screenobject responsible for remembering the position of an image at each point in time. The associated PTB texture can be drawn by invoking the draw() method. The classifier can request the location of the image at any point in time, using the getXY() and getX0Y0() methods.
Public Member Functions
IvGraphic (name, texture, x, y, width, height, winhandle, auxParameters)
IvGraphic Constructor.
function delete ()
IvGraphic Destructor.
function draw (winhandle, varargin)
Convenience wrapper for DrawTexture; if used should be called immediately after set().
function setXY (x, y, t)
Log mean XY position(s) at specified timepoint(s). If no presentation time is specified, will assume the current time. If xy has changed since previous, turns stationarity off.
function nudge (x, y)
Increment current x and y positions.
function reset (x, y, width, height)
Sets XY, and resets the history (n.b., may want to save the buffer history first?). If no values specified, will return to whereever it started.
function xy = getXY (t)
Get mean xy position (in pixels) prior to each time specified timepoint (or the most recent point if no time specified).
function xy = getX0Y0 (t)
Get top-left xy position (in pixels) prior to each time specified timepoint (or the most recent point if no time specified).
function y = getY ()
Get current mean Y position (in pixels).
function saveBuffer (src, evnt)
Output xyt log to an external CSV file, linked in name to the appropriate IvDataLog file.
Public Member Functions inherited from ivis.graphic.IvScreenObject
function
type_code = type ()
Returns screen object code (e.g., TYPE_PRIOR, or TYPE_GRAPHIC).
Public Member Functions inherited from ivis.broadcaster.IvListener
function delete ()
Object destructor.
function startListening (eventName, functionHandle)
Inform broadcaster to execute the specified functionHandle whenever a given event with name eventName occurs.
function stopListening (eventName)
Stop listening to broadcast event.
function toggleListening (eventName, functionHandle)
Toggle whether or not subscribed to event (if not already subscribed a valid function handle must be supplied).
function startListeningTo (hostObj, hostProperty, eventName, functionHandle)
Add a listener for a property change in a given object.
Static Public Member Functions
static function [
texs ,
rects ,
imgs ] = loadAll (directory, ext, winhandle)
loadAll helper/convenience function for loading all image files (with a given file extension) from a specified directory (returns the texture handles)
Public Attributes
nullrect
name
user specified parameters
texture
winhandle
srcrect
width
height
auxParameters
to pass to Screen(DrawTexture) - i.e., see procedural gabor demo
isStationary = true
other internal parameters
xyt
an Nx3 CExpandableBuffer with starting N as specified in params
plotColour = "b"
Additional Inherited Members
Static Public Attributes inherited from ivis.graphic.IvScreenObject
static const TYPE_PRIOR = 1
static const TYPE_GRAPHIC = 2
static const TYPE_GRAPHICCOMPOUND = 3
Protected Member Functions inherited from ivis.graphic.IvScreenObject
IvScreenObject (type)
IvScreenObject Constructor.
Detailed Description
Screenobject responsible for remembering the position of an image at each point in time. The associated PTB texture can be drawn by invoking the draw() method. The classifier can request the location of the image at any point in time, using the getXY() and getX0Y0() methods.
IvGraphic Methods
IvGraphic - Constructor.
draw - Convenience wrapper for DrawTexture; if used should be called immediately after set().
setXY - Log mean XY position(s) at specified timepoint(s).
nudge - Increment current XY position
reset - Sets XY, and resets the history (n.b., may want to save the buffer history first?).
getXY - Get mean xy position (in pixels) prior to each time specified timepoint (or the most recent point if no time specified).
getX0Y0 - Get top-left xy position (in pixels) prior to each time specified timepoint (or the most recent point if no time specified).
getX - Get current mean X position (in pixels).
getY - Get current mean Y position (in pixels).
saveBuffer - Output xyt log to an external CSV file, linked in name to the appropriate IvDataLog file.
IvGraphic Static Methods:
loadAll - convert all image files from a given directory into textures
See Also
none
Example
none
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.0 PJ 02/2013 : first_build
Todo:
: check getX0Y0
: delete setXY and reinitXY
Copyright 2014 : P R Jones
Definition at line 19 of file IvGraphic.m.
Constructor & Destructor Documentation
ivis.graphic.IvGraphic.IvGraphic (name, texture, x, y, width, height, winhandle, auxParameters)
IvGraphic Constructor.
Parameters
name String specifying the name of the graphical object
texture A PTB-3 texture handle
x The centre position, in pixels, along the horizontal axis [0 == left]
y The centre position, in pixels, along the vertical axis [0 == top]
width The width of the graphic, in pixels
height The height of the graphic, in pixels
winhandle PTB-3 screen handle
auxParameters Cell of optional aditional parameters passed to PTBs Screen(DrawTexture'...). E.g., for procedural texture generation
Returns
IvGraphic IvGraphic handle
Date
26/06/14
Author
PRJ
Definition at line 132 of file IvGraphic.m.
Member Function Documentation
function ivis.graphic.IvGraphic.delete ()
IvGraphic Destructor.
Date
26/06/14
Author
PRJ
Definition at line 190 of file IvGraphic.m.
References ivis.broadcaster.Screen().
function ivis.graphic.IvGraphic.draw (winhandle, varargin) virtual
Convenience wrapper for DrawTexture; if used should be called immediately after set().
Parameters
winhandle handle to PTB-3 screen, onto which the texture will be drawn
varargin Optional aditional parameters passed to PTBs Screen(DrawTexture'...). E.g., for procedural texture generation. If blank, will use any auxParameters specified during construction
Date
26/06/14
Author
PRJ
Implements ivis.graphic.IvScreenObject.
Definition at line 217 of file IvGraphic.m.
References ivis.broadcaster.Screen().
function xy = ivis.graphic.IvGraphic.getX0Y0 (t)
Get top-left xy position (in pixels) prior to each time specified timepoint (or the most recent point if no time specified).
Parameters
t Optional vector of times. The XY position immediately prior to each time will be returned. If empty, will return the current XY.
Returns
xy 2D vector, giving x and y coordinates (from top-left of screen, to top-left of object)
Date
26/06/14
Author
PRJ
Definition at line 385 of file IvGraphic.m.
function xy = ivis.graphic.IvGraphic.getXY (t)
Get mean xy position (in pixels) prior to each time specified timepoint (or the most recent point if no time specified).
Parameters
t Optional vector of times. The XY position immediately prior to each time will be returned. If empty, will return the current XY.
Returns
xy 2D vector, giving x and y coordinates (from top-left of screen, to middle of object)
Date
26/06/14
Author
PRJ
Definition at line 357 of file IvGraphic.m.
function y = ivis.graphic.IvGraphic.getY ()
Get current mean Y position (in pixels).
Returns
y New centre position, in pixels, along the vertical axis [0 == top].
Date
26/06/14
Author
PRJ
Definition at line 430 of file IvGraphic.m.
function [ texs , rects , imgs ] = ivis.graphic.IvGraphic.loadAll (directory, ext, winhandle) static
loadAll helper/convenience function for loading all image files (with a given file extension) from a specified directory (returns the texture handles)
Parameters
directory relative or absolute path to folder containing images
ext file extension (e.g., png)
winhandle PTB-3 screen handle, with which textures will be created
Returns
texs cell of texture handles
rects cell of image dimensions [0 0 width height]
imgs cell of RGBA matrices
Date
26/06/14
Author
PRJ
Definition at line 504 of file IvGraphic.m.
References ivis.broadcaster.Screen().
function ivis.graphic.IvGraphic.nudge (x, y)
Increment current x and y positions.
Parameters
x Num pixels to incremement X position by
y Num pixels to incremement X position by
Date
26/06/14
Author
PRJ
Definition at line 294 of file IvGraphic.m.
function ivis.graphic.IvGraphic.reset (x, y, width, height) virtual
Sets XY, and resets the history (n.b., may want to save the buffer history first?). If no values specified, will return to whereever it started.
Parameters
x The centre position, in pixels, along the horizontal axis [0 == left]
y The centre position, in pixels, along the vertical axis [0 == top]
width The width of the graphic, in pixels
height The height of the graphic, in pixels
Date
26/06/14
Author
PRJ
Implements ivis.graphic.IvScreenObject.
Definition at line 317 of file IvGraphic.m.
function ivis.graphic.IvGraphic.saveBuffer (src, evnt)
Output xyt log to an external CSV file, linked in name to the appropriate IvDataLog file.
Parameters
src
evnt
Date
26/06/14
Author
PRJ
Required fields of evnt:
Definition at line 446 of file IvGraphic.m.
function ivis.graphic.IvGraphic.setXY (x, y, t)
Log mean XY position(s) at specified timepoint(s). If no presentation time is specified, will assume the current time. If xy has changed since previous, turns stationarity off.
Parameters
x The centre position, in pixels, along the horizontal axis [0 == left]. If empty, will repeat previous.
y The centre position, in pixels, along the vertical axis [0 == top]. If empty, will repeat previous.
t The expected presentation time. If empty, will use the current time, under the assumption that the graphic is going to be presented (i.e. Flipped) ASAP
Date
26/06/14
Author
PRJ
Definition at line 248 of file IvGraphic.m.
Member Data Documentation
ivis.graphic.IvGraphic.auxParameters
to pass to Screen(DrawTexture) - i.e., see procedural gabor demo
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 90 of file IvGraphic.m.
ivis.graphic.IvGraphic.height
Definition at line 89 of file IvGraphic.m.
ivis.graphic.IvGraphic.isStationary = true
other internal parameters
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: true
Definition at line 99 of file IvGraphic.m.
ivis.graphic.IvGraphic.name
user specified parameters
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 76 of file IvGraphic.m.
ivis.graphic.IvGraphic.nullrect
Definition at line 72 of file IvGraphic.m.
ivis.graphic.IvGraphic.plotColour = "b"
Definition at line 121 of file IvGraphic.m.
ivis.graphic.IvGraphic.srcrect
Definition at line 87 of file IvGraphic.m.
ivis.graphic.IvGraphic.texture
Definition at line 85 of file IvGraphic.m.
ivis.graphic.IvGraphic.width
Definition at line 88 of file IvGraphic.m.
ivis.graphic.IvGraphic.winhandle
Definition at line 86 of file IvGraphic.m.
ivis.graphic.IvGraphic.xyt
an Nx3 CExpandableBuffer with starting N as specified in params
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 109 of file IvGraphic.m.
The documentation for this class was generated from the following file:
src/+ivis/+graphic/IvGraphic.m