ivis: Singleton Class Reference
Singleton Class Reference abstract
A pseudo-singleton class pattern for Matlab.
Protected Member Functions
Singleton ()
The internal singleton reference (bit of a hack, thanks to Matlab not having static properties).
Static Protected Member Functions
static function obj = getSetSingleton (obj)
.
static function obj = initialise (classname, varargin)
Initialise the Singleton.
static function init = isinit (classname)
Confirm whether the Singleton has been initialised.
static function obj = getInstanceSingleton (classname, varargin)
Get object (only 1 can exist).
static function finishUpSingleton (classname)
Delete object.
Detailed Description
A pseudo-singleton class pattern for Matlab.
Note that the constructor of any class that inherets from this should be
hidden thus
 methods (Access = ?Singleton)
     function obj=MyClass()
   end
 end
And the following blurb pasted in (e.g., at the end of the class)
methods (Static, Access = ?Singleton) function obj = getSetSingleton(obj) persistent singleObj if nargin > 0, singleObj = obj; end obj = singleObj; end end methods (Static, Access = public) function obj = init() obj = Singleton.initialise(mfilename(class)); end function obj = getInstance() obj = Singleton.getInstanceSingleton(mfilename(class)); end function [] = finishUp() Singleton.finishUpSingleton(mfilename(class)); end end
In this way the only initialisation point is via MyClass.init()
Note that the blurb would not be necessary if Matlab provided
a) Static variables b) Any means of determining the name of a class calling a static parent method
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.0 PJ 02/2013 : first_build
1.1 PJ 06/2013 : updated documentation
Copyright 2014 : P R Jones
Note
This class has the class property Abstract and needs to be inherited in order to be instantiable.
Definition at line 17 of file Singleton.m.
Constructor & Destructor Documentation
Singleton.Singleton () protected
The internal singleton reference (bit of a hack, thanks to Matlab not having static properties).
Date
26/06/14
Author
PRJ
Definition at line 84 of file Singleton.m.
References SingletonManager.add().
Member Function Documentation
function Singleton.finishUpSingleton (classname) static protected
Delete object.
Parameters
classname String containing child class name
Date
26/06/14
Author
PRJ
Definition at line 223 of file Singleton.m.
References SingletonManager.remove().
Referenced by MyDemoInputHandler.finishUp(), ivis.gui.IvGUIwebcam.finishUp(), ivis.broadcaster.IvBroadcaster.finishUp(), ivis.gui.IvGUIclassifierVector.finishUp(), ivis.gui.IvGUIclassifierBox.finishUp(), ivis.gui.IvGUIeyetrackSpatial.finishUp(), ivis.gui.IvGUIclassifierGrid.finishUp(), ivis.gui.IvGUIclassifierLL.finishUp(), ivis.gui.IvGUIclassifier.finishUp(), ivis.video.IvWebcam.finishUp(), ivis.gui.IvGUIeyetrackTemporal.finishUp(), ivis.log.IvRawLog.finishUp(), ivis.math.IvUnitHandler.finishUp(), ivis.gui.IvGUI.finishUp(), ivis.gui.IvGUIcalibration.finishUp(), ivis.log.IvDataLog.finishUp(), ivis.calibration.IvCalibration.finishUp(), ivis.main.IvParams.finishUp(), ivis.video.IvVideo.finishUp(), ivis.video.TrackBox.finishUp(), ivis.audio.IvAudio.finishUp(), and ivis.eyetracker.IvDataInput.finishUp().
function obj = Singleton.getInstanceSingleton (classname, varargin) static protected
Get object (only 1 can exist).
Parameters
classname String containing child class name
varargin Misc
Returns
obj Singleton object
Date
26/06/14
Author
PRJ
Definition at line 191 of file Singleton.m.
Referenced by MyDemoInputHandler.getInstance(), ivis.gui.IvGUIwebcam.getInstance(), ivis.broadcaster.IvBroadcaster.getInstance(), ivis.gui.IvGUIclassifierVector.getInstance(), ivis.gui.IvGUIclassifierBox.getInstance(), ivis.gui.IvGUIeyetrackSpatial.getInstance(), ivis.gui.IvGUIclassifierGrid.getInstance(), ivis.gui.IvGUIclassifierLL.getInstance(), ivis.gui.IvGUIclassifier.getInstance(), ivis.video.IvWebcam.getInstance(), ivis.gui.IvGUIeyetrackTemporal.getInstance(), ivis.log.IvRawLog.getInstance(), ivis.math.IvUnitHandler.getInstance(), ivis.gui.IvGUI.getInstance(), ivis.gui.IvGUIcalibration.getInstance(), ivis.log.IvDataLog.getInstance(), ivis.calibration.IvCalibration.getInstance(), ivis.main.IvParams.getInstance(), ivis.video.IvVideo.getInstance(), ivis.video.TrackBox.getInstance(), ivis.audio.IvAudio.getInstance(), and ivis.eyetracker.IvDataInput.getInstance().
function obj = Singleton.getSetSingleton (obj) static protected pure virtual
.
Date
26/06/14
Author
PRJ
Note
This method has non-standard access specifiers: Access = (Singleton)
Implemented in ivis.eyetracker.IvDataInput, ivis.audio.IvAudio, ivis.video.TrackBox, ivis.video.IvVideo, ivis.main.IvParams, ivis.calibration.IvCalibration, ivis.log.IvDataLog, ivis.gui.IvGUIcalibration, ivis.gui.IvGUI, ivis.log.IvRawLog, ivis.math.IvUnitHandler, ivis.gui.IvGUIeyetrackTemporal, ivis.video.IvWebcam, ivis.gui.IvGUIclassifier, ivis.gui.IvGUIclassifierLL, ivis.gui.IvGUIeyetrackSpatial, ivis.gui.IvGUIclassifierBox, ivis.gui.IvGUIclassifierVector, ivis.broadcaster.IvBroadcaster, and ivis.gui.IvGUIwebcam.
function obj = Singleton.initialise (classname, varargin) static protected
Initialise the Singleton.
Parameters
classname String containing child class name
varargin Misc
Returns
obj Singleton object
Date
26/06/14
Author
PRJ
Definition at line 140 of file Singleton.m.
References isinit().
Referenced by ivis.video.IvVideo.init().
function init = Singleton.isinit (classname) static protected
Confirm whether the Singleton has been initialised.
Parameters
classname String containing child class name
Returns
init Boolean
Date
26/06/14
Author
PRJ
Definition at line 167 of file Singleton.m.
Referenced by initialise().
The documentation for this class was generated from the following file:
src/ivis_util/Singleton.m