ivis: ivis.video.TrackBox Class Reference
ivis.video.TrackBox Class Reference
Display Tobii eyetracker box schema and current eyeball info.
Public Member Functions
TrackBox ()
TrackBox Constructor.
function delete ()
IvWebcam Desctructor.
function draw (unused1, unused2)
.
function start ()
.
function stop ()
.
Public Member Functions inherited from ivis.broadcaster.IvListener
function delete ()
Object destructor.
function startListening (eventName, functionHandle)
Inform broadcaster to execute the specified functionHandle whenever a given event with name eventName occurs.
function stopListening (eventName)
Stop listening to broadcast event.
function toggleListening (eventName, functionHandle)
Toggle whether or not subscribed to event (if not already subscribed a valid function handle must be supplied).
function startListeningTo (hostObj, hostProperty, eventName, functionHandle)
Add a listener for a property change in a given object.
Static Public Member Functions
static function obj = getInstance ()
static function finishUp ()
Public Attributes
winhandle
eyeTracker
monitorwidth_mm = 365
monitorheight_mm = 270
monitorwidth_px
monitorheight_px
tobiidist = 150
boxdist_mm = 600
boxsize_mm = 300
amax
Public Attributes inherited from ivis.broadcaster.IvListener
listenerHandles = {""}
listener handles
eventNames = {""}
event names
Static Public Attributes
static const ALLOW_IMPLICIT_CONSTRUCTION = true
Static Protected Member Functions
static function obj = getSetSingleton (obj)
.
Static Protected Member Functions inherited from Singleton
static function obj = initialise (classname, varargin)
Initialise the Singleton.
static function init = isinit (classname)
Confirm whether the Singleton has been initialised.
static function obj = getInstanceSingleton (classname, varargin)
Get object (only 1 can exist).
static function finishUpSingleton (classname)
Delete object.
Additional Inherited Members
Protected Member Functions inherited from Singleton
Singleton ()
The internal singleton reference (bit of a hack, thanks to Matlab not having static properties).
Detailed Description
Display Tobii eyetracker box schema and current eyeball info.
Utility function that displays a scale wireframe model of the display screen and Tobii x120 trackbox. Estimated eyeball and fixation positions are displayed, or the wireframe is turned red if no input is detected. The screen parameters are taken from IvParams. However, the track box dimensions are guestimated and hardcoded, since they cannot be extracted from the Tobii given the current matlab SDK bindings.
TrackBox Methods
draw - Draw trackbox, and keep updating until stopped
stop - Stop drawing trackbox and release memory
toggle - Alternate between start/stop states
See Also
none
Example
none
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.0 PJ 03/2013 : first_build
@ todo: Should probably be refactored to be part of a Tobii-specific package (or even inside the Tobii class itself)
Copyright 2014 : P R Jones
Note
This class has the class property Sealed and cannot be derived from.
Definition at line 19 of file TrackBox.m.
Constructor & Destructor Documentation
ivis.video.TrackBox.TrackBox ()
TrackBox Constructor.
Returns
obj TrackBox object
Date
26/06/14
Author
PRJ
Definition at line 182 of file TrackBox.m.
References ivis.broadcaster.Screen().
Member Function Documentation
function ivis.video.TrackBox.delete ()
IvWebcam Desctructor.
Date
26/06/14
Author
PRJ
Definition at line 297 of file TrackBox.m.
function ivis.video.TrackBox.draw (unused1, unused2)
.
Date
26/06/14
Author
PRJ
Parameters
unused1 Marked as "~" in original m-file.
unused2 Marked as "~" in original m-file.
Definition at line 312 of file TrackBox.m.
References ivis.broadcaster.Screen().
static function ivis.video.TrackBox.finishUp () static
Definition at line 650 of file TrackBox.m.
References Singleton.finishUpSingleton().
static function obj = ivis.video.TrackBox.getInstance () static
Definition at line 646 of file TrackBox.m.
References Singleton.getInstanceSingleton().
static function obj = ivis.video.TrackBox.getSetSingleton (obj) static protected virtual
.
Date
26/06/14
Author
PRJ
Note
This method has non-standard access specifiers: Access = (Singleton)
Implements Singleton.
Definition at line 638 of file TrackBox.m.
function ivis.video.TrackBox.start ()
.
Date
26/06/14
Author
PRJ
Definition at line 426 of file TrackBox.m.
function ivis.video.TrackBox.stop ()
.
Date
26/06/14
Author
PRJ
Definition at line 439 of file TrackBox.m.
Member Data Documentation
const ivis.video.TrackBox.ALLOW_IMPLICIT_CONSTRUCTION = true static
Definition at line 69 of file TrackBox.m.
ivis.video.TrackBox.amax
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 161 of file TrackBox.m.
ivis.video.TrackBox.boxdist_mm = 600
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 600
Definition at line 141 of file TrackBox.m.
ivis.video.TrackBox.boxsize_mm = 300
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 300
Definition at line 151 of file TrackBox.m.
ivis.video.TrackBox.eyeTracker
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 84 of file TrackBox.m.
ivis.video.TrackBox.monitorheight_mm = 270
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 270
Definition at line 103 of file TrackBox.m.
ivis.video.TrackBox.monitorheight_px
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 122 of file TrackBox.m.
ivis.video.TrackBox.monitorwidth_mm = 365
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 365
Definition at line 93 of file TrackBox.m.
ivis.video.TrackBox.monitorwidth_px
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 113 of file TrackBox.m.
ivis.video.TrackBox.tobiidist = 150
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 150
Definition at line 131 of file TrackBox.m.
ivis.video.TrackBox.winhandle
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 75 of file TrackBox.m.
The documentation for this class was generated from the following file:
src/+ivis/+video/TrackBox.m