ivis: SingletonManager Class Reference
SingletonManager Class Reference
Singleton manager class that maintains references to each Singleton object (and provides a mechanism to find and/or delete all Singletons).
Static Public Member Functions
static function add (classname)
Register specified Singleton.
static function remove (classname)
Delete specified Singleton.
static function clearAll (verbosity)
Delete all Singletons. Print info to the console.
static function listAll ()
Print the names of all extant Singletons to the console.
Detailed Description
Singleton manager class that maintains references to each Singleton object (and provides a mechanism to find and/or delete all Singletons).
Singleton Static Methods
add - Register specified Singleton.
remove - Delete specified Singleton.
clearAll - Delete all Singletons.
listAll - Print the names of all extant singletons to the console.
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.0 PJ 02/2013 : first_build
1.1 PJ 06/2013 : updated documentation
Copyright 2014 : P R Jones
Definition at line 17 of file SingletonManager.m.
Member Function Documentation
function SingletonManager.add (classname) static
Register specified Singleton.
Parameters
classname String containing child class name
Date
26/06/14
Author
PRJ
Definition at line 114 of file SingletonManager.m.
Referenced by Singleton.Singleton().
function SingletonManager.clearAll (verbosity) static
Delete all Singletons. Print info to the console.
Parameters
verbosity Numeric verbosity flag
Date
26/06/14
Author
PRJ
Definition at line 146 of file SingletonManager.m.
Referenced by ivis.main.IvMain.finishUp(), and ivis.test.Test_IvUnitHandler.setUp().
function SingletonManager.listAll () static
Print the names of all extant Singletons to the console.
Date
26/06/14
Author
PRJ
Definition at line 165 of file SingletonManager.m.
function SingletonManager.remove (classname) static
Delete specified Singleton.
Parameters
classname String containing child class name
Date
26/06/14
Author
PRJ
Definition at line 130 of file SingletonManager.m.
Referenced by Singleton.finishUpSingleton(), and ivis.eyetracker.IvDataInput.init().
The documentation for this class was generated from the following file:
src/ivis_util/SingletonManager.m