ivis: ivis.video.IvVideo Class Reference
ivis.video.IvVideo Class Reference
Video singleton for loading, playing and controlling videos.
Public Member Functions
IvVideo ()
IvVideo Constructor.
function delete ()
IvVideo destructor.
function movPtr = open (movieFn)
#.
function play (fullscreen, updateAutomatically)
#.
function tex = playFrame (unused1, unused2)
.
function stop ()
.
function close ()
.
function pause (keepDisplaying)
.
function unpause ()
.
function togglePause (keepDisplaying)
.
Public Member Functions inherited from ivis.broadcaster.IvListener
function delete ()
Object destructor.
function startListening (eventName, functionHandle)
Inform broadcaster to execute the specified functionHandle whenever a given event with name eventName occurs.
function stopListening (eventName)
Stop listening to broadcast event.
function toggleListening (eventName, functionHandle)
Toggle whether or not subscribed to event (if not already subscribed a valid function handle must be supplied).
function startListeningTo (hostObj, hostProperty, eventName, functionHandle)
Add a listener for a property change in a given object.
Static Public Member Functions
static function obj = init ()
static function obj = getInstance ()
static function finishUp ()
Public Attributes
defaultVidDir
defaultVidFns
nVidFns
moviePtr
movieFn
movieNum = 1
playRate = 1
frameCount = 0
winhandle
fullscreen = false
dstRect = "[]"
tex
wasAudioEnabled = false
background = "[128, 128, 128]"
screen background RGB (max 255)
blocking = 1
Use blocking wait for new frames by default.
preloadsecs = 1
defaults to 1second
pixelFormat = 4
4 is the default for colour, 5 or 6 may provide significantly improved playback performance on modern GPUs.
maxThreads = "[]"
a setting of zero asks to auto-select an optimum number of threads for a given computer
shader = "[]"
volume = .35
isPaused = false
Public Attributes inherited from ivis.broadcaster.IvListener
listenerHandles = {""}
listener handles
eventNames = {""}
event names
Static Public Attributes
static const WAIT_PERIOD = .005
Static Protected Member Functions
static function obj = getSetSingleton (obj)
.
Static Protected Member Functions inherited from Singleton
static function obj = initialise (classname, varargin)
Initialise the Singleton.
static function init = isinit (classname)
Confirm whether the Singleton has been initialised.
static function obj = getInstanceSingleton (classname, varargin)
Get object (only 1 can exist).
static function finishUpSingleton (classname)
Delete object.
Additional Inherited Members
Protected Member Functions inherited from Singleton
Singleton ()
The internal singleton reference (bit of a hack, thanks to Matlab not having static properties).
Detailed Description
Video singleton for loading, playing and controlling videos.
Videos can be made to update/play automatically on every flip, by using play/pause/unpause (which registers the IvVideo object up to the ivis event broadcaster). Alternatively each frame can be updated manually using playFrame(). New video files can be loaded using open(), which acts as a wrapper for Screen(OpenMovie). Videos are closed automatically on IvMain.finishUp().
IvVideo Methods
IvVideo - Constructor
open - Open movie file
play - Play movie buffer
playFrame - Play single frame from movie buffer
stop - Stop the movie and restore audio
close - Close movie and release memory
pause - Stop the movie from updating
unpause - Restore movie updating
togglePause - Alternate between paused/unpaused state
See Also
none
Example
none
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.0 PJ 03/2013 : first_build
Copyright 2014 : P R Jones
Note
This class has the class property Sealed and cannot be derived from.
Definition at line 19 of file IvVideo.m.
Constructor & Destructor Documentation
ivis.video.IvVideo.IvVideo ()
IvVideo Constructor.
Returns
obj IvVideo object
Date
26/06/14
Author
PRJ
Definition at line 298 of file IvVideo.m.
Member Function Documentation
function ivis.video.IvVideo.close ()
.
Date
26/06/14
Author
PRJ
Definition at line 518 of file IvVideo.m.
References ivis.broadcaster.Screen().
function ivis.video.IvVideo.delete ()
IvVideo destructor.
Date
26/06/14
Author
PRJ
Definition at line 322 of file IvVideo.m.
static function ivis.video.IvVideo.finishUp () static
Definition at line 641 of file IvVideo.m.
References Singleton.finishUpSingleton().
static function obj = ivis.video.IvVideo.getInstance () static
Definition at line 637 of file IvVideo.m.
References Singleton.getInstanceSingleton().
static function obj = ivis.video.IvVideo.getSetSingleton (obj) static protected virtual
.
Date
26/06/14
Author
PRJ
Note
This method has non-standard access specifiers: Access = (Singleton)
Implements Singleton.
Definition at line 625 of file IvVideo.m.
static function obj = ivis.video.IvVideo.init () static
Definition at line 633 of file IvVideo.m.
References Singleton.initialise().
function movPtr = ivis.video.IvVideo.open (movieFn)
#.
Parameters
movieFn #####
Returns
movPtr #####
Date
26/06/14
Author
PRJ
Definition at line 337 of file IvVideo.m.
References ivis.broadcaster.Screen().
function ivis.video.IvVideo.pause (keepDisplaying)
.
Parameters
keepDisplaying ######
Date
26/06/14
Author
PRJ
Definition at line 549 of file IvVideo.m.
References ivis.broadcaster.Screen().
function ivis.video.IvVideo.play (fullscreen, updateAutomatically)
#.
Parameters
fullscreen #####
updateAutomatically #####
Date
26/06/14
Author
PRJ
Definition at line 380 of file IvVideo.m.
References ivis.broadcaster.Screen().
function tex = ivis.video.IvVideo.playFrame (unused1, unused2)
.
Returns
tex ######
Date
26/06/14
Author
PRJ
tex empty if eof
Parameters
unused1 Marked as "~" in original m-file.
unused2 Marked as "~" in original m-file.
Definition at line 437 of file IvVideo.m.
References ivis.broadcaster.Screen().
function ivis.video.IvVideo.stop ()
.
Date
26/06/14
Author
PRJ
Definition at line 493 of file IvVideo.m.
function ivis.video.IvVideo.togglePause (keepDisplaying)
.
Parameters
keepDisplaying ######
Date
26/06/14
Author
PRJ
Definition at line 593 of file IvVideo.m.
function ivis.video.IvVideo.unpause ()
.
Date
26/06/14
Author
PRJ
Definition at line 575 of file IvVideo.m.
References ivis.broadcaster.Screen().
Member Data Documentation
ivis.video.IvVideo.background = "[128, 128, 128]"
screen background RGB (max 255)
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: "[128, 128, 128]"
Definition at line 207 of file IvVideo.m.
ivis.video.IvVideo.blocking = 1
Use blocking wait for new frames by default.
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 1
Definition at line 217 of file IvVideo.m.
ivis.video.IvVideo.defaultVidDir
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 80 of file IvVideo.m.
ivis.video.IvVideo.defaultVidFns
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 89 of file IvVideo.m.
ivis.video.IvVideo.dstRect = "[]"
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: "[]"
Definition at line 176 of file IvVideo.m.
ivis.video.IvVideo.frameCount = 0
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 0
Definition at line 145 of file IvVideo.m.
ivis.video.IvVideo.fullscreen = false
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: false
Definition at line 166 of file IvVideo.m.
ivis.video.IvVideo.isPaused = false
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: false
Definition at line 278 of file IvVideo.m.
ivis.video.IvVideo.maxThreads = "[]"
a setting of zero asks to auto-select an optimum number of threads for a given computer
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: "[]"
Definition at line 247 of file IvVideo.m.
ivis.video.IvVideo.movieFn
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 116 of file IvVideo.m.
ivis.video.IvVideo.movieNum = 1
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 1
Definition at line 125 of file IvVideo.m.
ivis.video.IvVideo.moviePtr
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 107 of file IvVideo.m.
ivis.video.IvVideo.nVidFns
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 98 of file IvVideo.m.
ivis.video.IvVideo.pixelFormat = 4
4 is the default for colour, 5 or 6 may provide significantly improved playback performance on modern GPUs.
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 4
Definition at line 237 of file IvVideo.m.
ivis.video.IvVideo.playRate = 1
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 1
Definition at line 135 of file IvVideo.m.
ivis.video.IvVideo.preloadsecs = 1
defaults to 1second
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 1
Definition at line 227 of file IvVideo.m.
ivis.video.IvVideo.shader = "[]"
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: "[]"
Definition at line 257 of file IvVideo.m.
ivis.video.IvVideo.tex
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 187 of file IvVideo.m.
ivis.video.IvVideo.volume = .35
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: .35
Definition at line 267 of file IvVideo.m.
ivis.video.IvVideo.WAIT_PERIOD = .005 static
Default: .005
Definition at line 70 of file IvVideo.m.
ivis.video.IvVideo.wasAudioEnabled = false
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: false
Definition at line 196 of file IvVideo.m.
ivis.video.IvVideo.winhandle
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 156 of file IvVideo.m.
The documentation for this class was generated from the following file:
src/+ivis/+video/IvVideo.m