ivis: ivis.gui.IvGUIwebcam Class Reference
ivis.gui.IvGUIwebcam Class Reference
Singleton for displaying webcam feed in a GUI.
Public Member Functions
IvGUIwebcam (GUIidx, resolution)
IvWebcam Constructor.
function update (tex)
Update figure window.
Public Member Functions inherited from ivis.gui.IvGUIelement
function delete ()
IvGUIelement Destructor.
Static Public Member Functions
static function obj = getInstance ()
static function finishUp ()
Public Attributes
hImage
Public Attributes inherited from ivis.gui.IvGUIelement
hFig
Static Public Attributes
static const FIG_NAME = "IvGUIwebcam"
Static Public Attributes inherited from ivis.gui.IvGUIelement
static const FIG_NAME
Static Protected Member Functions
static function obj = getSetSingleton (obj)
.
Additional Inherited Members
Protected Member Functions inherited from ivis.gui.IvGUIelement
function [
effectiveFDims ,
fDims ,
aDims ] = init (GUIidx, normaliseDims, bgcolor)
Initialise the GUI element; set the renderer and compute the plot area dimensions.
Detailed Description
Singleton for displaying webcam feed in a GUI.
IvGUIwebcam Methods
IvGUIwebcam - Constructor.
update - Update figure window.
See Also
ivis.video.IvWebcam
Example
none
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.0 PJ 07/2013 : first_build
Todo:
add pausetoggle button(s)
Copyright 2014 : P R Jones
Note
This class has the class property Sealed and cannot be derived from.
Definition at line 19 of file IvGUIwebcam.m.
Constructor & Destructor Documentation
ivis.gui.IvGUIwebcam.IvGUIwebcam (GUIidx, resolution)
IvWebcam Constructor.
Parameters
GUIidx GUI frame index
resolution expected image size (pixels)
Returns
obj IvVideo object
Date
26/06/14
Author
PRJ
Definition at line 72 of file IvGUIwebcam.m.
Member Function Documentation
static function ivis.gui.IvGUIwebcam.finishUp () static
Definition at line 129 of file IvGUIwebcam.m.
References Singleton.finishUpSingleton().
static function obj = ivis.gui.IvGUIwebcam.getInstance () static
Definition at line 125 of file IvGUIwebcam.m.
References Singleton.getInstanceSingleton().
static function obj = ivis.gui.IvGUIwebcam.getSetSingleton (obj) static protected virtual
.
Date
26/06/14
Author
PRJ
Note
This method has non-standard access specifiers: Access = (Singleton)
Implements Singleton.
Definition at line 117 of file IvGUIwebcam.m.
function ivis.gui.IvGUIwebcam.update (tex)
Update figure window.
Parameters
tex image texture
Date
26/06/14
Author
PRJ
Definition at line 94 of file IvGUIwebcam.m.
References ivis.broadcaster.Screen().
Member Data Documentation
const ivis.gui.IvGUIwebcam.FIG_NAME = "IvGUIwebcam" static
Definition at line 56 of file IvGUIwebcam.m.
ivis.gui.IvGUIwebcam.hImage
Definition at line 61 of file IvGUIwebcam.m.
The documentation for this class was generated from the following file:
+ivis/+gui/IvGUIwebcam.m