ivis: SingletonManager Class Reference
SingletonManager Class Reference
todo: implement verbosity n.b., this cannot be part of Singleton, in case class gets cleared (?)
Static Public Member Functions
static function add (classname)
static function remove (classname)
static function clearAll (verbosity)
static function listAll ()
Detailed Description
todo: implement verbosity n.b., this cannot be part of Singleton, in case class gets cleared (?)
Definition at line 17 of file SingletonManager.m.
Member Function Documentation
static function SingletonManager.add (classname) static
Definition at line 74 of file SingletonManager.m.
Referenced by Singleton.Singleton().
static function SingletonManager.clearAll (verbosity) static
Definition at line 85 of file SingletonManager.m.
Referenced by ivis.main.IvMain.finishUp(), and ivis.test.Test_IvUnitHandler.setUp().
static function SingletonManager.listAll () static
Definition at line 93 of file SingletonManager.m.
static function SingletonManager.remove (classname) static
Definition at line 80 of file SingletonManager.m.
Referenced by Singleton.finishUpSingleton(), and ivis.eyetracker.IvDataInput.init().
The documentation for this class was generated from the following file:
src/ivis_util/SingletonManager.m