ivis: CStack Class Reference
CStack Class Reference
CStack define a stack data strcuture.
Public Member Functions
CStack (c)
function s = size ()
function remove ()
function b = empty ()
function b = isempty ()
function push (el)
function el = top ()
function el = pop ()
function display ()
function c = content ()
Detailed Description
CStack define a stack data strcuture.
It likes java.util.Stack, however, it could use CStack.content() to return all the data (in cells) of the Stack, and it is a litter faster than java's Stack.
s = CStack(c); c is a cells, and could be omitted s.size() return the numble of element s.isempty() return true when the stack is empty s.empty() delete the content of the stack s.push(el) push el to the top of stack s.pop() pop out the top of the stack, and return the element s.top() return the top element of the stack s.remove() remove all the elements in the stack s.content() return all the data of the stack (in the form of a cells with size [s.size(), 1]
See Also
CList, CQueue
CList, CQueue
Copyright: zhang.nosp@m.@zhi.nosp@m.qiang.nosp@m..org, 2010. url: http://zhiqiang.org/blog/it/matlab-data-structures.html
Definition at line 17 of file CStack.m.
Constructor & Destructor Documentation
CStack.CStack (c)
Definition at line 62 of file CStack.m.
Member Function Documentation
function c = CStack.content ()
Definition at line 144 of file CStack.m.
function CStack.display ()
Definition at line 132 of file CStack.m.
function b = CStack.empty ()
Definition at line 90 of file CStack.m.
function b = CStack.isempty ()
Definition at line 96 of file CStack.m.
Referenced by ellipse(), enableDisableFig(), findjobj(), getjframe(), getTween(), hline(), enableDisableFig>getJFrame(), and getjframe>getJFrame().
function el = CStack.pop ()
Definition at line 121 of file CStack.m.
function CStack.push (el)
Definition at line 101 of file CStack.m.
function CStack.remove ()
Definition at line 85 of file CStack.m.
function s = CStack.size ()
Definition at line 80 of file CStack.m.
Referenced by ellipse(), findjobj(), and getTween().
function el = CStack.top ()
Definition at line 111 of file CStack.m.
The documentation for this class was generated from the following file:
src/ivis_util/CStack.m