ivis: ivis.gui.IvGUIclassifierLL Class Reference
ivis.gui.IvGUIclassifierLL Class Reference
Singleton for displaying log-likelihood classifier parameters and status.
Public Member Functions
IvGUIclassifierLL (GUIidx, lMagThresh, graphicObjs, hitFuncs)
IvGUIclassifierLL Constructor.
function update (newPlot1Dat, plot2Dat)
Update figure window.
Public Member Functions inherited from ivis.gui.IvGUIclassifier
virtual function update (newPlot1Dat, plot2Dat, varargin)
Update figure window.
function reset ()
Reset the classifier panel; clear any accumulated data.
function printStatus (statusCode, gObjLookingAt)
Write the classification estimate to the panel.
Public Member Functions inherited from ivis.gui.IvGUIelement
function delete ()
IvGUIelement Destructor.
Static Public Member Functions
static function obj = getInstance ()
static function finishUp ()
Static Public Member Functions inherited from ivis.gui.IvGUIclassifier
static function obj = getInstance ()
static function finishUp ()
Public Attributes
graphicObjs
other internal parameters
hitFuncs
Static Public Attributes
static const FIG_NAME = "IvGUIclassifierLL"
Static Public Attributes inherited from ivis.gui.IvGUIclassifier
static const BUFFER_LENGTH = 100
Static Public Attributes inherited from ivis.gui.IvGUIelement
static const FIG_NAME
Static Protected Member Functions
static function obj = getSetSingleton (obj)
.
Additional Inherited Members
Protected Member Functions inherited from ivis.gui.IvGUIelement
function [
effectiveFDims ,
fDims ,
aDims ] = init (idx, normaliseDims, bgcolor)
Initialise the GUI element; set the renderer and compute the plot area dimensions.
Protected Attributes inherited from ivis.gui.IvGUIclassifier
plot1Data
data buffers top panel data (location)
plot2Data
bottom panel data (evidence)
nAlternatives
integer num hypotheses handles
hPlot1Data
top panel data handle
hPlot2Data
bottom panel data handle
hPlot2Text
bottom panel text handle
Detailed Description
Singleton for displaying log-likelihood classifier parameters and status.
IvGUIclassifierLL Methods
IvGUIclassifierLL - Constructor.
update - Update figure window.
See Also
ivis.classifier.IvClassifierLL
Example
none
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.1 PJ 02/2013 : converted to Singleton
1.0 PJ 02/2013 : first_build
Todo:
rename plots with discriptive names (spatial/temporal rather than plot1 plot2)
Copyright 2014 : P R Jones
Note
This class has the class property Sealed and cannot be derived from.
Definition at line 19 of file IvGUIclassifierLL.m.
Constructor & Destructor Documentation
ivis.gui.IvGUIclassifierLL.IvGUIclassifierLL (GUIidx, lMagThresh, graphicObjs, hitFuncs)
IvGUIclassifierLL Constructor.
Parameters
GUIidx #######
lMagThresh #######
graphicObjs #######
hitFuncs #######
Returns
obj IvGUIclassifierLL object
Date
26/06/14
Author
PRJ
Definition at line 85 of file IvGUIclassifierLL.m.
References hline(), IvHline(), and textLoc().
Member Function Documentation
static function ivis.gui.IvGUIclassifierLL.finishUp () static
Definition at line 214 of file IvGUIclassifierLL.m.
References Singleton.finishUpSingleton().
static function obj = ivis.gui.IvGUIclassifierLL.getInstance () static
Definition at line 210 of file IvGUIclassifierLL.m.
References Singleton.getInstanceSingleton().
static function obj = ivis.gui.IvGUIclassifierLL.getSetSingleton (obj) static protected virtual
.
Date
26/06/14
Author
PRJ
Note
This method has non-standard access specifiers: Access = (Singleton)
Reimplemented from ivis.gui.IvGUIclassifier.
Definition at line 202 of file IvGUIclassifierLL.m.
function ivis.gui.IvGUIclassifierLL.update (newPlot1Dat, plot2Dat)
Update figure window.
Parameters
newPlot1Dat
plot2Dat
Date
26/06/14
Author
PRJ
Definition at line 169 of file IvGUIclassifierLL.m.
Member Data Documentation
const ivis.gui.IvGUIclassifierLL.FIG_NAME = "IvGUIclassifierLL" static
Definition at line 60 of file IvGUIclassifierLL.m.
ivis.gui.IvGUIclassifierLL.graphicObjs
other internal parameters
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 65 of file IvGUIclassifierLL.m.
ivis.gui.IvGUIclassifierLL.hitFuncs
Definition at line 74 of file IvGUIclassifierLL.m.
The documentation for this class was generated from the following file:
src/+ivis/+gui/IvGUIclassifierLL.m