ivis: ivis.video.IvWebcam Class Reference
ivis.video.IvWebcam Class Reference
Webcam singleton for displaying webcam feed in a GUI.
Public Member Functions
IvWebcam (GUIidx, deviceId)
IvWebcam Constructor.
function delete ()
function draw (unused1, unused2)
Retrieve the latest image from the video input buffer, and draw it onto the GUI.
Public Member Functions inherited from ivis.broadcaster.IvListener
function delete ()
Object destructor.
function startListening (eventName, functionHandle)
Inform broadcaster to execute the specified functionHandle whenever a given event with name eventName occurs.
function stopListening (eventName)
Stop listening to broadcast event.
function toggleListening (eventName, functionHandle)
Toggle whether or not subscribed to event (if not already subscribed a valid function handle must be supplied).
function startListeningTo (hostObj, hostProperty, eventName, functionHandle)
Add a listener for a property change in a given object.
Static Public Member Functions
static function listDevices ()
Wrapper for Screen(VideoCaptureDevices).
static function obj = getInstance ()
static function finishUp ()
Public Attributes
winhandle
handle to PTB screen
videoGrabber
handle to webcam interface
resolution
webcam resolution [w h] pixels
guiElement
handle to Ivis GUI element
Public Attributes inherited from ivis.broadcaster.IvListener
listenerHandles = {""}
listener handles
eventNames = {""}
event names
Static Protected Member Functions
static function obj = getSetSingleton (obj)
.
Static Protected Member Functions inherited from Singleton
static function obj = initialise (classname, varargin)
Initialise the Singleton.
static function init = isinit (classname)
Confirm whether the Singleton has been initialised.
static function obj = getInstanceSingleton (classname, varargin)
Get object (only 1 can exist).
static function finishUpSingleton (classname)
Delete object.
Additional Inherited Members
Protected Member Functions inherited from Singleton
Singleton ()
The internal singleton reference (bit of a hack, thanks to Matlab not having static properties).
Detailed Description
Webcam singleton for displaying webcam feed in a GUI.
IvWebcam Methods
IvWebcam - Constructor.
draw - Retrieve the latest image from the video input buffer, and draw it onto the GUI.
IvWebcam Static Methods
listDevices - Wrapper for Screen(VideoCaptureDevices)
See Also
none
Example
none
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.0 PJ 07/2013 : first_build
Todo:
: check if specified deviceId is valid
: handle device detection
Copyright 2014 : P R Jones
Note
This class has the class property Sealed and cannot be derived from.
Definition at line 19 of file IvWebcam.m.
Constructor & Destructor Documentation
ivis.video.IvWebcam.IvWebcam (GUIidx, deviceId)
IvWebcam Constructor.
Parameters
GUIidx Ivis GUI element index
deviceId Optional id of the webcam hardware
Returns
obj IvWebcam object
Date
26/06/14
Author
PRJ
Definition at line 108 of file IvWebcam.m.
References ivis.broadcaster.Screen().
Member Function Documentation
function ivis.video.IvWebcam.delete ()
Definition at line 156 of file IvWebcam.m.
References ivis.broadcaster.Screen().
function ivis.video.IvWebcam.draw (unused1, unused2)
Retrieve the latest image from the video input buffer, and draw it onto the GUI.
Date
26/06/14
Author
PRJ
Parameters
unused1 Marked as "~" in original m-file.
unused2 Marked as "~" in original m-file.
Definition at line 162 of file IvWebcam.m.
References ivis.broadcaster.Screen().
static function ivis.video.IvWebcam.finishUp () static
Definition at line 224 of file IvWebcam.m.
References Singleton.finishUpSingleton().
static function obj = ivis.video.IvWebcam.getInstance () static
Definition at line 220 of file IvWebcam.m.
References Singleton.getInstanceSingleton().
static function obj = ivis.video.IvWebcam.getSetSingleton (obj) static protected virtual
.
Date
26/06/14
Author
PRJ
Note
This method has non-standard access specifiers: Access = (Singleton)
Implements Singleton.
Definition at line 212 of file IvWebcam.m.
function ivis.video.IvWebcam.listDevices () static
Wrapper for Screen(VideoCaptureDevices).
Date
26/06/14
Author
PRJ
Definition at line 191 of file IvWebcam.m.
References ivis.broadcaster.Screen().
Member Data Documentation
ivis.video.IvWebcam.guiElement
handle to Ivis GUI element
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 89 of file IvWebcam.m.
ivis.video.IvWebcam.resolution
webcam resolution [w h] pixels
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 80 of file IvWebcam.m.
ivis.video.IvWebcam.videoGrabber
handle to webcam interface
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 71 of file IvWebcam.m.
ivis.video.IvWebcam.winhandle
handle to PTB screen
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 62 of file IvWebcam.m.
The documentation for this class was generated from the following file:
src/+ivis/+video/IvWebcam.m