ivis: CExpandableBuffer Class Reference
CExpandableBuffer Class Reference
matrix data-structure that expands by a factor when capacity is exceeded.
Public Member Functions
CExpandableBuffer (n, m, expansionFactor)
CExpandableBuffer Constructor.
function put (x)
put Add data row(s).
function [ y ,
ni ] = get (ni, mi)
get Get rows at specified indices (blank input for all).
function y = getN (n, mi)
getN Get N rows (first start).
function y = getLastN (n, mi)
getLastN Get N rows (from end).
function y = getLastNnonNaN (n, mi)
getLastNnonNaN Get N rows (from end), discounting any rows with NaNs in.
function
nrows_nonNaN = computeNnonNaN (mi)
function y = getBeforeEach (A, testCol, mi)
getBeforeEach Return elements in column K where elements in column J immediately precede values specified in A.
function y = getAfterX (X, testCol, mi)
getAfterX Return elements in column K where elements in column J > X.
function y = getEqual (X, testCol, mi)
getEqual Return elements in column K where elements in column J equal specified values.
function [ n ,
m ] = nElements ()
nElements Get {nrows, ncols}
function clear ()
clear Reset counters and set all elements to NaN (maintain final capacity).
Static Public Member Functions
static function unitTests ()
Unit tests --------------------------------------------------— Unit test main entry point.
static function testVector ()
Unit Test.
static function testMatrix ()
Unit Test.
static function testSpeed ()
Unit Test.
Public Attributes
capacity
max n data rows
ncols
n data columns
expansionFactor
amount to multiply capacity by
nrows = 0
internal nElements counter
Static Public Attributes
static const DEFAULT_EXPANSION_FACTOR = 2
default amount to multiply capacity by
Detailed Description
matrix data-structure that expands by a factor when capacity is exceeded.
n.b., columns inputs only! although it can expand, it is always best to allocate sufficient memory in advance, where possible. for example usage, see: CExpandableBuffer.unitTests();
CExpandableBuffer Methods
CExpandableBuffer - Constructor
put - Add data row(s)
get - Get rows at specified indices (blank input for all)
getN - Get N rows (first start)
getLastN - Get N rows (from end)
getBeforeEach - Return elements in column K where elements in column J immediately precede the values specified in A
getAfterX - Return elements in column K where elements in column J > X
getEqual - Return elements in column K where elements in column J equal specified values
nElements - Get {nrows, ncols}
clear - Reset counters and set all elements to NaN (maintain final capacity)
See Also
CCircularBuffer
Example
x = CExpandableBuffer(10,3), x.put([1 2 3; 11 12 13]), x.get()
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.0 PJ 03/2013 : first_build
Todo: Abstract some methods to a generic Buffer class?
Copyright 2014 : P R Jones
Definition at line 17 of file CExpandableBuffer.m.
Constructor & Destructor Documentation
CExpandableBuffer.CExpandableBuffer (n, m, expansionFactor)
CExpandableBuffer Constructor.
obj = CExpandableBuffer(n[,m=1][, expansionFactor=2])
Parameters
n initial n data rows (int)
m n data columns (int)
expansionFactor amount to increase "n" by once 90 percent capacity exceeded (float)
Returns
obj CExpandableBuffer object
Date
26/06/14
Author
PRJ
Definition at line 132 of file CExpandableBuffer.m.
References DEFAULT_EXPANSION_FACTOR, and expansionFactor.
Referenced by testMatrix(), testSpeed(), and testVector().
Member Function Documentation
function CExpandableBuffer.clear ()
clear Reset counters and set all elements to NaN (maintain final capacity).
obj.clear()
Date
26/06/14
Author
PRJ
Definition at line 453 of file CExpandableBuffer.m.
Referenced by clearAbsAll().
function nrows_nonNaN = CExpandableBuffer.computeNnonNaN (mi)
Definition at line 334 of file CExpandableBuffer.m.
function [ y , ni ] = CExpandableBuffer.get (ni, mi)
get Get rows at specified indices (blank input for all).
y = obj.get([ni][, mi])
Parameters
ni row indices
mi col indices
Returns
y data rows (float)
Date
26/06/14
Author
PRJ
Definition at line 202 of file CExpandableBuffer.m.
function y = CExpandableBuffer.getAfterX (X, testCol, mi)
getAfterX Return elements in column K where elements in column J > X.
y = obj.getAfterX(X, testCol[, mi])
Parameters
X value to test against [float scalar]
testCol column num to test A against (int)
mi column indices to return
Returns
y data rows (float)
Date
26/06/14
Author
PRJ
Definition at line 379 of file CExpandableBuffer.m.
function y = CExpandableBuffer.getBeforeEach (A, testCol, mi)
getBeforeEach Return elements in column K where elements in column J immediately precede values specified in A.
y = obj.getBeforeEach(A, testCol[, mi])
Parameters
A values to test against [column of floats]
testCol column num to test A against (int)
mi column indices to return
Returns
y data rows (float)
Date
26/06/14
Author
PRJ
may start to be unacceptably slow as the n points increases
Definition at line 345 of file CExpandableBuffer.m.
function y = CExpandableBuffer.getEqual (X, testCol, mi)
getEqual Return elements in column K where elements in column J equal specified values.
y = obj.getEqual(X, testCol[, mi])
Parameters
X value to test against [float scalar]
testCol column num to test A against (int)
mi column indices to return
Returns
y data rows (float)
Date
26/06/14
Author
PRJ
Definition at line 406 of file CExpandableBuffer.m.
function y = CExpandableBuffer.getLastN (n, mi)
getLastN Get N rows (from end).
y = obj.getLastN(n[, mi])
Parameters
n n rows (int)
mi col indices
Returns
y data rows (float)
Date
26/06/14
Author
PRJ
Definition at line 264 of file CExpandableBuffer.m.
function y = CExpandableBuffer.getLastNnonNaN (n, mi)
getLastNnonNaN Get N rows (from end), discounting any rows with NaNs in.
y = obj.getLastNnonNaN(n[, mi])
Parameters
n n rows (int)
mi col indices
Returns
y data rows (float)
Date
26/06/14
Author
PRJ
Definition at line 297 of file CExpandableBuffer.m.
function y = CExpandableBuffer.getN (n, mi)
getN Get N rows (first start).
y = obj.getN(n[, mi])
Parameters
n number of rows to return
mi col indices
Returns
y data rows (float)
Date
26/06/14
Author
PRJ
Definition at line 231 of file CExpandableBuffer.m.
function [ n , m ] = CExpandableBuffer.nElements ()
nElements Get {nrows, ncols}
[n,m] = obj.nElements()
Returns
n nrows
m ncols
Date
26/06/14
Author
PRJ
Definition at line 433 of file CExpandableBuffer.m.
function CExpandableBuffer.put (x)
put Add data row(s).
obj.put(x)
Parameters
x data rows (float)
Date
26/06/14
Author
PRJ
Definition at line 166 of file CExpandableBuffer.m.
function CExpandableBuffer.testMatrix () static
Unit Test.
Date
26/06/14
Author
PRJ
Definition at line 547 of file CExpandableBuffer.m.
References CExpandableBuffer().
function CExpandableBuffer.testSpeed () static
Unit Test.
Date
26/06/14
Author
PRJ
Definition at line 581 of file CExpandableBuffer.m.
References CExpandableBuffer().
function CExpandableBuffer.testVector () static
Unit Test.
Date
26/06/14
Author
PRJ
Definition at line 494 of file CExpandableBuffer.m.
References CExpandableBuffer().
function CExpandableBuffer.unitTests () static
Unit tests --------------------------------------------------— Unit test main entry point.
Date
26/06/14
Author
PRJ
Definition at line 479 of file CExpandableBuffer.m.
References testSuiteFromStatic().
Member Data Documentation
CExpandableBuffer.capacity
max n data rows
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 86 of file CExpandableBuffer.m.
CExpandableBuffer.DEFAULT_EXPANSION_FACTOR = 2 static
default amount to multiply capacity by
Default: 2
Definition at line 67 of file CExpandableBuffer.m.
Referenced by CExpandableBuffer().
CExpandableBuffer.expansionFactor
amount to multiply capacity by
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 104 of file CExpandableBuffer.m.
Referenced by CExpandableBuffer().
CExpandableBuffer.ncols
n data columns
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 95 of file CExpandableBuffer.m.
CExpandableBuffer.nrows = 0
internal nElements counter
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Default: 0
Definition at line 113 of file CExpandableBuffer.m.
The documentation for this class was generated from the following file:
ivis_util/CExpandableBuffer.m