ivis: CCircularBuffer Class Reference
CCircularBuffer Class Reference
circular-buffer (or: ring buffer) data-structure.
Public Member Functions
CCircularBuffer (m, n)
CCircularBuffer Constructor.
function [ buff ,
y ] = put (x)
put Add data row(s)
function y = getN (n, mi)
getN return the specified number of elements.
function y = get (ni, mi)
get return the elements at specified indices
function [ n ,
m ] = nElements ()
nElements Get {nrows, ncols}.
function clear ()
clear Reset counters and set all elements to NaN.
Static Public Member Functions
static function unitTests ()
Unit tests --------------------------------------------------— Unit test main entry point.
static function testVector ()
Unit Test.
static function testMatrix ()
Unit Test.
static function testSpeed ()
Unit Test.
Public Attributes
capacity
max n data rows
ncols
n data columns
Detailed Description
circular-buffer (or: ring buffer) data-structure.
FiFo: first-in first-out n.b., columns inputs only! for example usage, see: CCircularBuffer.unitTests();
CCircularBuffer Methods
CCircularBuffer - Constructor
put - Add data row(s)
get - Get rows at specified indices (blank input for all)
getN - Get N rows
nElements - Get {nrows, ncols}
clear - Reset counters and set all elements to NaN
See Also
CExpandableBuffer
Example
x = CCircularBuffer(10), y = x.put((1:20)')
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.0 PJ 03/2013 : first_build
Todo: add examples to function docs?
Copyright 2014 : P R Jones
Definition at line 17 of file CCircularBuffer.m.
Constructor & Destructor Documentation
CCircularBuffer.CCircularBuffer (m, n)
CCircularBuffer Constructor.
obj = CCircularBuffer(n[, m=1])
Parameters
m initial num data rows (int)
n num data columns (int)
Returns
obj CCircularBuffer object
Date
26/06/14
Author
PRJ
Definition at line 108 of file CCircularBuffer.m.
Referenced by testMatrix(), testSpeed(), and testVector().
Member Function Documentation
function CCircularBuffer.clear ()
clear Reset counters and set all elements to NaN.
obj.clear()
Date
26/06/14
Author
PRJ
Definition at line 261 of file CCircularBuffer.m.
function y = CCircularBuffer.get (ni, mi)
get return the elements at specified indices
y = obj.get([ni][, mi])
Parameters
ni row indices
mi col indices
Returns
y data rows (float)
Date
26/06/14
Author
PRJ
Definition at line 207 of file CCircularBuffer.m.
function y = CCircularBuffer.getN (n, mi)
getN return the specified number of elements.
y = obj.getN([n][, mi])
Parameters
n number of elements to return
mi col indices
Returns
y data rows (float)
Date
26/06/14
Author
PRJ
Definition at line 176 of file CCircularBuffer.m.
function [ n , m ] = CCircularBuffer.nElements ()
nElements Get {nrows, ncols}.
[n,m] = obj.nElements()
Returns
n nrows
m ncols
Date
26/06/14
Author
PRJ
Definition at line 241 of file CCircularBuffer.m.
function [ buff , y ] = CCircularBuffer.put (x)
put Add data row(s)
y = obj.put(x)
Parameters
x data rows (float)
Returns
y any overwritten rows (float)
Date
26/06/14
Author
PRJ
Definition at line 139 of file CCircularBuffer.m.
function CCircularBuffer.testMatrix () static
Unit Test.
Date
26/06/14
Author
PRJ
Definition at line 364 of file CCircularBuffer.m.
References CCircularBuffer().
function CCircularBuffer.testSpeed () static
Unit Test.
Date
26/06/14
Author
PRJ
Definition at line 393 of file CCircularBuffer.m.
References CCircularBuffer().
function CCircularBuffer.testVector () static
Unit Test.
Date
26/06/14
Author
PRJ
Definition at line 301 of file CCircularBuffer.m.
References CCircularBuffer().
function CCircularBuffer.unitTests () static
Unit tests --------------------------------------------------— Unit test main entry point.
Date
26/06/14
Author
PRJ
Definition at line 286 of file CCircularBuffer.m.
References testSuiteFromStatic().
Member Data Documentation
CCircularBuffer.capacity
max n data rows
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 79 of file CCircularBuffer.m.
CCircularBuffer.ncols
n data columns
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 88 of file CCircularBuffer.m.
The documentation for this class was generated from the following file:
src/ivis_util/CCircularBuffer.m