ivis: ivis.math.IvUnitHandler Class Reference
ivis.math.IvUnitHandler Class Reference
Utility singleton for converting between distances on screen (cm, px, dg)
Public Member Functions
IvUnitHandler (screenWidth_cm, screenWidth_px, viewingDist_cm)
IvUnitHandler Constructor.
function y_px = cm2px (x_cm)
Convert cm to pixels.
function y = px2deg (x_px, viewingDist_cm)
Convert pixels to degrees visual angle.
function y = deg2px (x_deg, viewingDist_cm)
Convert degrees visual angle to pixels.
function y_cm = deg2cm (x_deg, viewingDist_cm)
Convert degrees visual angle to cm.
Static Public Member Functions
static function obj = getInstance ()
static function finishUp ()
Public Attributes
screenWidth_px
user specified parameters info
screenWidth_cm
djfksdhfajk
viewingDist_cm
dfdfdf
pixel_per_cm
other internal parameters dfdfdf
screenWidth_dg
dfdfdf
pixel_per_dg
dfdfdf
maxFreq_cpd
dfdfdf
Static Protected Member Functions
static function obj = getSetSingleton (obj)
.
Static Protected Member Functions inherited from Singleton
static function obj = initialise (classname, varargin)
Initialise the Singleton.
static function init = isinit (classname)
Confirm whether the Singleton has been initialised.
static function obj = getInstanceSingleton (classname, varargin)
Get object (only 1 can exist).
static function finishUpSingleton (classname)
Delete object.
Additional Inherited Members
Protected Member Functions inherited from Singleton
Singleton ()
The internal singleton reference (bit of a hack, thanks to Matlab not having static properties).
Detailed Description
Utility singleton for converting between distances on screen (cm, px, dg)
Note that these conversions require setup-specific info, regarding the dimensions of the monitor, the screen resolution, and the distance of the observer to the screen. The singleton object should be informed about these things upon initialisation.
IvUnitHandler Methods
IvUnitHandler - Constructor.
px2cm - Convert pixels to cm.
px2deg - Convert pixels to degrees visual angle.
deg2px - Convert degrees visual angle to pixels.
cm2px - Convert cm to pixels.
cm2deg - Convert cm to degrees visual angle.
deg2cm - Convert degrees visual angle to cm.
See Also
ivis.math.IvUnitHandler
Example
runtests infantvision.tests -verbose
Author
Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Verinfo
1.1 PJ 02/2011 : used to develop commenting standards
1.0 PJ 02/2011 : first_build
Copyright 2014 : P R Jones
Note
This class has the class property Sealed and cannot be derived from.
Definition at line 19 of file IvUnitHandler.m.
Constructor & Destructor Documentation
ivis.math.IvUnitHandler.IvUnitHandler (screenWidth_cm, screenWidth_px, viewingDist_cm)
IvUnitHandler Constructor.
Parameters
screenWidth_cm monitor screen width, in cm
screenWidth_px monitor screen width, in px
viewingDist_cm distance from eye to monitor, in cm
Returns
obj IvUnitHandler object
Date
26/06/14
Author
PRJ
Definition at line 143 of file IvUnitHandler.m.
References rad2deg().
Member Function Documentation
function y_px = ivis.math.IvUnitHandler.cm2px (x_cm)
Convert cm to pixels.
Parameters
x_cm
Returns
y_deg
Date
26/06/14
Author
PRJ
Definition at line 183 of file IvUnitHandler.m.
function y_cm = ivis.math.IvUnitHandler.deg2cm (x_deg, viewingDist_cm)
Convert degrees visual angle to cm.
Parameters
x_deg
viewingDist_cm
Returns
y_cm
Date
26/06/14
Author
PRJ
Definition at line 253 of file IvUnitHandler.m.
function y = ivis.math.IvUnitHandler.deg2px (x_deg, viewingDist_cm)
Convert degrees visual angle to pixels.
Parameters
x_deg
viewingDist_cm
Returns
y
Date
26/06/14
Author
PRJ
Definition at line 227 of file IvUnitHandler.m.
References rad2deg().
static function ivis.math.IvUnitHandler.finishUp () static
Definition at line 295 of file IvUnitHandler.m.
References Singleton.finishUpSingleton().
static function obj = ivis.math.IvUnitHandler.getInstance () static
Definition at line 291 of file IvUnitHandler.m.
References Singleton.getInstanceSingleton().
static function obj = ivis.math.IvUnitHandler.getSetSingleton (obj) static protected virtual
.
Date
26/06/14
Author
PRJ
Note
This method has non-standard access specifiers: Access = (Singleton)
Implements Singleton.
Definition at line 283 of file IvUnitHandler.m.
function y = ivis.math.IvUnitHandler.px2deg (x_px, viewingDist_cm)
Convert pixels to degrees visual angle.
Parameters
x_px
viewingDist_cm
Returns
y
Date
26/06/14
Author
PRJ
Definition at line 201 of file IvUnitHandler.m.
References rad2deg().
Member Data Documentation
ivis.math.IvUnitHandler.maxFreq_cpd
dfdfdf
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 124 of file IvUnitHandler.m.
ivis.math.IvUnitHandler.pixel_per_cm
other internal parameters dfdfdf
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 96 of file IvUnitHandler.m.
ivis.math.IvUnitHandler.pixel_per_dg
dfdfdf
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 115 of file IvUnitHandler.m.
ivis.math.IvUnitHandler.screenWidth_cm
djfksdhfajk
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 77 of file IvUnitHandler.m.
ivis.math.IvUnitHandler.screenWidth_dg
dfdfdf
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 106 of file IvUnitHandler.m.
ivis.math.IvUnitHandler.screenWidth_px
user specified parameters info
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 67 of file IvUnitHandler.m.
ivis.math.IvUnitHandler.viewingDist_cm
dfdfdf
Note
This property has non-standard access specifiers: SetAccess = Private, GetAccess = Public
Matlab documentation of property attributes.
Definition at line 86 of file IvUnitHandler.m.
The documentation for this class was generated from the following file:
src/+ivis/+math/IvUnitHandler.m