ivis: src/ivis_util/clearAbsAll.m File Reference
clearAbsAll.m File Reference
Clear command window: clc;.
Functions
function clearAbsAll ()
Clear command window: clc;.
Detailed Description
Clear command window: clc;.
Definition in file clearAbsAll.m.
Function Documentation
function clearAbsAll ()
Clear command window: clc;.
Definition at line 17 of file clearAbsAll.m.
References CExpandableBuffer.clear().
Referenced by ivisDemo002_keyboardHandling(), ivisDemo003_mouseTracking(), ivisDemo004_eyeTracking(), ivisDemo005_usingaPTBScreen(), ivisDemo006_trackboxVisualisation(), ivisDemo007_classifyingFixations(), ivisDemo008_playingVideos(), ivisDemo009_streamingWebcams(), ivisDemo010_readingRawGazeData(), ivisDemo011_advancedClassifiers(), ivisDemo012_externalConfigFiles(), ivisDemo_audio(), and ivis.main.IvMain.totalClear().