ivis: ivisDemos/ivisDemo008_playingVideos.m File Reference
ivisDemo008_playingVideos.m File Reference
ivisDemo008_playingVideos. Displaying a video file on a PTB screen.
Functions
function ivisDemo008_playingVideos ()
ivisDemo008_playingVideos. Displaying a video file on a PTB screen.
Detailed Description
ivisDemo008_playingVideos. Displaying a video file on a PTB screen.
Definition in file ivisDemo008_playingVideos.m.
Function Documentation
function ivisDemo008_playingVideos ()
ivisDemo008_playingVideos. Displaying a video file on a PTB screen.
How to use IvVideo to play, pause and close videos. Note that we have now shifted to using function, because otherwise matlab throws errors with regards to calls to singleton getInstance() constructors. If you are running a 64-bit version of matlab don't forget that you will need to install GStreamer (and probably some additional packages)
If you are having problems then Psychtoolbox's MovieDemo.m might be a good place to start
Note that it is vital that the broadcaster package is imported (ivis.broadcaster.*), as this contains a wrapper for PTB's Screen(Flip) which ensures that screen update events are broadcasted throughout ivis.
Requires: ivis toolbox v1.3
Matlab: v2012 onwards
See Also
ivisDemo007_classifyingFixations.m ivisDemo009_streamingWebcams.m
Author(s): Pete R Jones petej.nosp@m.onze.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Version History: 1.0.0 PJ 22/06/2013 Initial build. 1.1.0 PJ 18/10/2013 General tidy up (ivis 1.4).
Copyright 2014 : P R Jones
clear memory and set workspace
Definition at line 17 of file ivisDemo008_playingVideos.m.
References clearAbsAll(), ivisdir(), and ivis.broadcaster.Screen().