ivis: ivis::broadcaster Namespace Reference
ivis::broadcaster Namespace Reference
Classes
class IvBroadcaster
Responsible for broadcasting event message to ivis components.
class IvEventData
Simple Event object wrapper specifying what properties an event should store (currently just a generic parameter called obj.Data).
class IvListener
Methods for pairing (or unpairing) an arbitrary function with a given broadcaster event name.
Functions
mlhsInnerSubst
< matlabtypesubstitute,
varargout > Screen (matlabtypesubstitute varargin)
SCREEN wrapper for PTB's Screen command.
Function Documentation
mlhsInnerSubst< matlabtypesubstitute, varargout > ivis::broadcaster::Screen (matlabtypesubstitute varargin)
SCREEN wrapper for PTB's Screen command.
Intercepts Screen command and inserts a PreFlip broadcast event before
any <tt>Flip</tt> commands
Note, because further objects may be drawn just prior to the final Flip, it is important NOT to use: Screen(DrawingFinished, winhandle) in your script!
 varargin   whatever PTB's Screen() requires
Returns:
   varargout   whatever PTB's Screen() returns
Requires: none
See Also
none
Matlab: v2008 onwards
Author(s): Pete R Jones
Version History: v1.0.0 18/06/14 Initial build. v1.0.1 20/01/11 ######
Copyright 2014 : P R Jones
Definition at line 19 of file Screen.m.
Referenced by ivis::video::IvVideo::close(), ivis::video::IvWebcam::delete(), ivis::graphic::IvGraphic::delete(), ivis::video::IvWebcam::draw(), ivis::classifier::IvClassifierGrid::draw(), ivis::classifier::IvClassifierLL::draw(), ivis::graphic::IvGraphic::draw(), ivis::classifier::IvClassifierVector::draw(), ivis::classifier::IvClassifierBox::draw(), ivis::calibration::TrackBox::draw(), ivis::main::IvMain::finishUp(), ivis::main::IvParams::getDefaultConfig(), ivis::main::IvParams::IvParams(), ivis::eyetracker::IvTobiiEyeX::IvTobiiEyeX(), ivis::video::IvWebcam::IvWebcam(), ivis::main::IvMain::launch(), ivis::video::IvWebcam::listDevices(), ivis::graphic::IvGraphic::loadAll(), myFlip(), ivis::video::IvVideo::open(), ivis::video::IvVideo::pause(), ivis::video::IvVideo::play(), ivis::video::IvVideo::playFrame(), ivis::main::IvParams::registerScreen(), ivis::eyetracker::IvDataInput::setFixationMarker(), ivis::calibration::TrackBox::TrackBox(), ivis::video::IvVideo::unpause(), and ivis::gui::IvGUIwebcam::update().