ivis: src/ivis_util/rad2deg.m File Reference
rad2deg.m File Reference
RAD2DEG Convert angles from radians to degrees.
Functions
function
angleInDegrees = rad2deg (angleInRadians)
RAD2DEG Convert angles from radians to degrees.
Detailed Description
RAD2DEG Convert angles from radians to degrees.
Definition in file rad2deg.m.
Function Documentation
function angleInDegrees = rad2deg (angleInRadians)
RAD2DEG Convert angles from radians to degrees.
RAD2DEG has been replaced by RADTODEG.
angleInDegrees = RAD2DEG(angleInRadians) converts angle units from radians to degrees.
Definition at line 17 of file rad2deg.m.
Referenced by ivis.math.IvUnitHandler.deg2px(), ivis.math.IvUnitHandler.IvUnitHandler(), and ivis.math.IvUnitHandler.px2deg().